### ISSUE TITLE
Secure Cell / Optional Context / Clarification

### ISSUE THREAD

**Issue by mobrio** [cossacklabs/themis#10]
Expressed in phpthemis terms we have:
```php
string phpthemis_scell_full_encrypt(string $password, string $message [, string $context])
array  phpthemis_scell_auto_encrypt(string $password, string $message [, string $context])
string phpthemis_scell_user_encrypt(string $password, string $message, string $context)

string phpthemis_scell_full_decrypt(string $password, string $encrypted_message [, string $context])
string phpthemis_scell_auto_decrypt(string $password, $encrypted_message string $additional_auth_data [, string $context])
string phpthemis_scell_user_decrypt(string $password, string $encrypted_message, string $context)

```
$context is optional for the "full" and "auto" variants but mandatory for the "user" variant. Documentation should make this variation (and the reasoning behind it) clear.

**Comment by mnaza** [comment]
In Seal mode and Token protect mode in most cases encryption in stron enough withoun additional context data. In this modes context data can be used for checking of correcctnes of data transfer, data replacements etc. All necessery for encryption data (iv, auth tag) will be generated and added permanently. But in Context imprint mode we not have such ability and need to get it from user.

**Comment by cossacklabs** [comment]
Will be added to the docs.

**Comment by cossacklabs** [comment]
Resolved in current version of PHP docs, will be propagated across the rest.
