### ISSUE TITLE
Packaged Distribution

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#101]
Time has come to talk about binary distribution of Themis. The aim is to simplify build process to a point where user issues commands to 2 package managers: one for system package (themis itself), second for wrapper. 

This is about experience, and even though we don't need it for our stuff, it's been privately asked for, a few times. 

Obviously, we'll do .deb for Debian/Ubuntu. Any other ideas what/where we could go with this?

**Comment by mobrio** [comment]
Logically .rpm for the Fedora/Centos/RHEL world?

**Comment by gene-eu** [comment]
Indeed. Anything else?

**Comment by knyar** [comment]
.deb and .rpm should be enough for Linux, I believe.
OS X users might find a [brew](http://brew.sh/) recipe useful.

**Comment by vixentael** [comment]
+1 to brew

**Comment by gene-eu** [comment]
after reading through plan looks as follows: 
- [ ] package them ourselves
- [ ] verify that downloadable packages / recipes work 
- [ ] make them downloadable from site at some point
- [ ] collect feedback
- [ ] push them when 0.9.4 is done

**Comment by gene-eu** [comment]
- In 0.9.3 we will ship .deb/.rpm from our side (@mnaza)
- for 0.9.4 we'll try to get into official reps and do it for mac os x

**Comment by mnaza** [comment]
#200

**Comment by vixentael** [comment]
I think, @mnaza PR has partially fixed an issue.

what are our next steps?

**Comment by popaaaandrei** [comment]
Guys, any status on this? I am having problems building this on macOS Sierra and a `brew install themis` would be very useful :D

**Comment by gene-eu** [comment]
@popaaaandrei: as soon as .deb/.rpm ones will work, brew will be done as well

**Comment by vixentael** [comment]
+1 to `brew install themis`

**Comment by vixentael** [comment]
I'm closing this issue, because now it's separated into several ones:

- #274
- #233
- #226
