### ISSUE TITLE
Segmentation fault in python3.4

### ISSUE THREAD

**Issue by Lagovas** [cossacklabs/themis#102]
```
Python 3.4.3 (default, Oct 12 2015, 13:56:10) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pythemis.scomparator import scomparator
>>> scomparator(b'asd')
Segmentation fault (core dumped)
```
In python3.5 code is working

**Comment by gene-eu** [comment]
can we address this urgently please, @mnaza?

**Comment by mnaza** [comment]
With Debian default python 3.4.2 work fine. 
Please, @Lagovas, post your target OS version.

**Comment by Lagovas** [comment]
[lagovas@localhost ~]$ uname -a
Linux localhost 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
[lagovas@localhost ~]$ python --version
Python 3.4.3

**Comment by mnaza** [comment]
Please check, @Lagovas
