### ISSUE TITLE
Error building react native after upgrade 0.15.2

### ISSUE THREAD

**Issue by djaffer** [cossacklabs/themis#1035]
```
Task failed with an exception.

-----------

* What went wrong:

Execution failed for task ':react-native-themis:compileReleaseJavaWithJavac'.

> error: invalid source release: 17

* Try:

> Run with --stacktrace option to get the stack trace.

> Run with --info or --debug option to get more log output.

> Run with --scan to get full insights.

==============================================================================

2: Task failed with an exception.

-----------
```

**Comment by vixentael** [comment]
Thank you @djaffer , we will take a look (cc @radetsky )

**Comment by radetsky** [comment]
What version of JDK are you using? Run ```java --version``` in your terminal.

**Comment by djaffer** [comment]
its react native eas build so not sure.

**Comment by djaffer** [comment]
Previous version works perfectly fine.

**Comment by radetsky** [comment]
Thank you, we will take a look at this case. Anyway, you can still use the previous version or local builds. I tested local builds yesterday. It works perfectly. But the local JDK is 17.

**Comment by djaffer** [comment]
Here you go
```
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See ********docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

561 actionable tasks: 561 executed

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.

-----------

* What went wrong:

Execution failed for task ':react-native-themis:compileReleaseJavaWithJavac'.

> error: invalid source release: 17

* Try:

> Run with --stacktrace option to get the stack trace.

> Run with --info or --debug option to get more log output.

> Run with --scan to get full insights.

```

**Comment by djaffer** [comment]
I also see this on expo. Maybe they are fixing it.
![image](https://github.com/cossacklabs/themis/assets/5740725/3bcba912-ee61-4bf7-ae48-e570aa072fc0)

**Comment by radetsky** [comment]
It seems to me that nodejs 18 support will not give the expected result. Maybe you need to update the expo sdk version, because a new project based on the latest expo sdk builds and works without any problems.  And we always recommend using the latest versions of React Native. 

In your case, the eas build system cannot recognize files that were compiled in Java version 17.

**Comment by djaffer** [comment]
thanks, the issue was node version/base image. In eas.json added image: latest attribute.

```
"ios": {
        "image": "latest",
      },
"android": {
        "image": "latest"
      }
```

**Comment by djaffer** [comment]
thanks the issue was node version/base image. In eas.json added image: latest 

```
"ios": {
        "image": "latest",
      },
"android": {
        "image": "latest"
      }
```
