### ISSUE TITLE
Probably found typo in docs

### ISSUE THREAD

**Issue by DandyDrop** [cossacklabs/themis#1048]
Visited https://docs.cossacklabs.com/themis/languages/wasm and saw this:
![image_2024-07-22_19-42-55](https://github.com/user-attachments/assets/268ee912-2a30-4c10-8ab5-64b11be37dd9)

Should there be a word "platform" instead of "platorm"?

**Comment by Lagovas** [comment]
yes, you are right. thanks for noticing. we will fix it.
feel free to contribute [into our docs](https://github.com/cossacklabs/product-docs), they are public and open for contribution

**Comment by Lagovas** [comment]
we have fixed it

**Comment by vixentael** [comment]
thank you @DandyDrop!
