### ISSUE TITLE
Themis Android crashes on devices with 16 KB page size

### ISSUE THREAD

**Issue by lehandriel** [cossacklabs/themis#1050]
**Describe the bug**
Themis Android crashes on devices with 16 KB page size.

**To Reproduce**
1. Create a virtual device with Android 15 and 16KB page size
2. Run docs/examples/android app on the created virtual device
3. App crashes

**Expected behavior**
App runs without a crash

**Environment (please complete the following information):**
- OS: Android 15
- Hardware: ARM 64-bit 16KB page size
- Themis version: 0.15.2
- Installation way:
   - built from source

**Additional context**
According to https://developer.android.com/guide/practices/page-sizes#compile-r26-lower a line:
```
target_link_options(themis_jni PRIVATE "-Wl,-z,max-page-size=16384")
```
should be added to the file:
```
jni/CMakeLists.txt
```

**Comment by vixentael** [comment]
oh wow thank you @lehandriel 
We will take a look and update CMakeLists and try to repack the build

**Comment by lehandriel** [comment]
i've prepared a potential pr bases on google requirements:
https://github.com/cossacklabs/themis/pull/1051

**Comment by lehandriel** [comment]
@vixentael do you plan to release a new version of `themis-android` containing this fix any time soon? :)

**Comment by radetsky** [comment]
We updated themis-android on GitHub and in the Maven repository. 
You may try to set dependency as 
```
implementation 'com.cossacklabs.com:themis:0.15.5'
```

**Comment by vixentael** [comment]
@lehandriel please try the updated Themis and let us know if it works for you!

**Comment by lehandriel** [comment]
@radetsky @vixentael works like a charm 👍 thanks! 🙂

**Comment by lehandriel** [comment]
@radetsky @vixentael works like a charm 👍 thanks! 🙂

**Comment by vixentael** [comment]
thank you @lehandriel for opening an issue and suggesting a fix!
thank you @radetsky for checking the fix, updating the example app, and releasing the updated Themis lib

**Comment by davidwico** [comment]
@radetsky can you release a new version for react-native-themis with that fix? it stayed behind on v 0.15.2

**Comment by davidwico** [comment]
cc @vixentael

**Comment by matice2** [comment]
@radetsky @vixentael We would also need version 0.15.5 of react-native-themis. Could you possibly release it? :)

**Comment by vixentael** [comment]
working on it 

https://github.com/cossacklabs/themis/pull/1063
