### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by cossacklabs** [cossacklabs/themis#11]
High-level objects are crippled by 'examplistic' approach to describing their functions. This works for some, but not for all. Every high-level language function should have a more formal description like this, to make people who are less interested in long experimentation sessions to only understand the function's syntax: 

(example taken based on problems with PHP docs): 
string **phpthemis_scell_full_encrypt**(string $password, string $message [,string $context]);
Description: Encrypts $message using $password and an optional $context.
Returns the encrypted message or an empty string on failure.

or 

array **phpthemis_scell_auto_split_encrypt**(string $password, string $message [,string $context]);
Description: Encrypts $message using $password and an optional $context. On success, returns an associative array containing string elements ‘encrypted_message’ and ‘additional_auth_data’. On failure an empty string is returned.

**Comment by mnaza** [comment]
need revision
https://github.com/cossacklabs/themis/wiki/2.4.2-PHP-Howto

**Comment by cossacklabs** [comment]
looks good, go on.

**Comment by ignat1** [comment]
Maybe, we should generate separate API reference (we already have doxygen comments for each API)

**Comment by cossacklabs** [comment]
I believe modern compact systems with a couple of calls per object can afford mixing it with main documentation and examples. One of typical pitfalls of separating general docs from call / function reference is the need to switch between docs to understand things which could be kept and understood on one page. 

Let's hear what others think?

**Comment by mnaza** [comment]
I agree. As for me then interface and example is in one doc it is more comfortable.
I correct docs and need review

**Comment by mobrio** [comment]
As a lazy(ish) PHP consumer I would be happy to read elsewhere for the finer detail of how objects work internally or why they are designed the way they are. But what I do want to know explicitly and completely is the interface - function, parameters and outputs. 

For example:
```php
$rsa_keys = phpthemis_gen_rsa_key_pair(); 
```
gets me the
 ```php 
array( 'public_key' => 'some binary key data', 'private_key' => 'some binary key data')
```
Now i can go forward and use the keys with say themis secure message thats fine. But what ***exactly*** is the binary key data? Algorithm? bit sizes ? Is it all in some valid DER structure such that i could do:
```php
$pem ="-----BEGIN PUBLIC KEY-----\n";
$pem.=implode("\n",str_split(base64_encode($rsa_keys['public_key']),64));
$pem.="\n-----END PUBLIC KEY-----";    
```
It's not that i particularly want to do that ... the point is that I should be able to understand whether it would be possible if i did want to.

Oh and small point ... note that markdown supports language specific syntax highlighting for code blocks as per examples above.

**Comment by cossacklabs** [comment]
Okay, how about a separate 'Object API' page in docs, if mixing doesn't work for all of you? @vixentael expressed similar opinion.

**Comment by cossacklabs** [comment]
We have a version of PHP docs (courtesy of private exchange between @mobrio, @mnaza and me) covering most of the problems mentioned in this issue, here: https://github.com/cossacklabs/themis/wiki/2.4.2-PHP-Howto

If, as a template, it's good enough, will ask Python contributor to refactor Python docs accordingly.

**Comment by vixentael** [comment]
part of #74 (already finished in the separate repo, should be merged)

**Comment by gene-eu** [comment]
New docs are online
