### ISSUE TITLE
Consider linking OpenSSL as dynamic framework in PodSpec

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#128]
Continue of issue #127.

Let's move from compiled OpenSSl as static lib to dynamic framework.

See comments
https://github.com/cossacklabs/themis/issues/127#issuecomment-241689744
https://github.com/cossacklabs/themis/issues/127#issuecomment-241708026

**Comment by vixentael** [comment]
See branch [dynamic frameworks](https://github.com/cossacklabs/themis/tree/podspec_dynamic_frameworks) for latest changes.


### Current state:

Example projects working fine.

Linting fails with errors:

`pod spec lint themis.podspec --subspec=themis --verbose --allow-warnings --fail-fast`

```
    - ERROR | [iOS] [themis] xcodebuild: Returned an unsuccessful exit code.
    - ERROR | [themis] xcodebuild:  /var/folders/1v/7l7m798s24g1xqrh1kdxb2mr0000gn/T/CocoaPods/Lint/App/main.m:1:1: error: use of '@import' when modules are disabled
    - ERROR | [themis] xcodebuild:  /var/folders/1v/7l7m798s24g1xqrh1kdxb2mr0000gn/T/CocoaPods/Lint/App/main.m:2:1: error: use of '@import' when modules are disabled
    - ERROR | [themis] xcodebuild:  /var/folders/1v/7l7m798s24g1xqrh1kdxb2mr0000gn/T/CocoaPods/Lint/App/main.m:3:1: error: use of '@import' when modules are disabled
```

**Comment by gene-eu** [comment]
are there any changes in the ecosystem we'd like to wait until we make final decision? 0.9.4 is coming at steady pace, need to decide whether there are actionable points here

**Comment by vixentael** [comment]
I'll check the current state of CocoaPods infrastructure and let you know. I don't think that we need to wait, anyway.

**Comment by vixentael** [comment]
That's still a problem. 0.9.4 podspec will still be using OpenSSl as static library.

**Comment by vixentael** [comment]
Status update.

I've updated branch [podspec_dynamic_frameworks](https://github.com/cossacklabs/themis/tree/podspec_dynamic_frameworks), merged from master.


Current state: can't make CocoaPods linting working successfully due to error mentioned above `error: use of '@import' when modules are disabled`.

Other ways to create dynamic frameworks:

- http://mrdekk.ru/2016/04/30/cocoapods-static-transitive-binary-dependencies/
- https://github.com/x2on/OpenSSL-for-iPhone/blob/master/create-openssl-framework.sh


Maintainers with similar problems:

- https://github.com/grpc/grpc/issues/4121#issuecomment-222231908
- https://github.com/grpc/grpc/pull/6849
- https://github.com/CocoaPods/CocoaPods/issues/4605

Using BoringSSL instead:

- https://github.com/grpc/grpc/pull/4235
- https://github.com/cristianbica/boringssl-podspec/blob/master/BoringSSL.podspec


Next steps:

Play a bit more with creating dynamic frameworks (ideally, podspec should not disable CLANG MODULES ('CLANG_ENABLE_MODULES' => 'NO'))

Try to switch to BoringSSL

**Comment by vixentael** [comment]
Woohoo, I think we can solve this issue when this PR will be merged:

https://github.com/levigroker/GRKOpenSSLFramework/pull/2

### Status update: 

1. I changed Themis.podspec dependency to [GRKOpenSSLFramework](https://github.com/levigroker/GRKOpenSSLFramework) (OpenSSL static libs wrapped into dynamic frameworks).

2. Xcode building problems solved by adding `#ifdef __OBJC__  ... #endif` lines into `openssl.h` file inside framework. In this case project is built successfully, no need to disable CLANG modules.

3. Podspec looks like this (GRKOpenSSLFramework version might be .3 after merging PR) --> https://raw.githubusercontent.com/cossacklabs/themis/podspec_dynamic_frameworks_GRKOpenSSLFramework/themis.podspec

4. Podspec passes `pod spec lint` validation successfully.

5. Latest changes are pushed to [podspec_dynamic_frameworks_GRKOpenSSLFramework](https://github.com/cossacklabs/themis/tree/podspec_dynamic_frameworks_GRKOpenSSLFramework) branch.


### Next steps:

- [ ] wait until [PR](https://github.com/levigroker/GRKOpenSSLFramework/pull/2) is merged
- [ ] update podspec to link to the updated GRKOpenSSLFramework version
- [ ] make sure that all example projects are building successfully
- [ ] merge changes to `release_0.9.5` branch
- [ ] enjoy

**Comment by vixentael** [comment]
I think it's solved now!
