### ISSUE TITLE
Swift 3 wrapper

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#141]
I want to migrate Swift wrapper to use Swift3.

Usually, iOS libraries support both Swift 2.3 and Swift 3 as separate branches or versions (f.e. you can use version 9.3 with Swift2.3 or version 9.4 with Swift 3 support).

What is the most preferable decision for us? Just drop Swift2.3 support and migrate to Swift3?

**Comment by valeriyvan** [comment]
Forget about 2.3, support 3!

**Comment by vixentael** [comment]
Migrated :)
