### ISSUE TITLE
New docs engine

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#142]
Based on feedback from some of our users and (even) developers, we will try to build stand-alone documentation hosting. 

We need opinions on: 
1. Should the docs be replicated to github wiki? If convenient documentation solution is chosen and implemented, should we even care about github wiki? 
2. What features would our users like to see on documentation site, apart from being able to read documentation in convenient fashion, obviously :) 

Motivation: 
- @lagovas has put a lot of effort into producing awesome tutorials, which do not fit neither our [blog](https://www.cossacklabs.com/blog/) nor github structure. 
- upon release of forthcoming products, keeping all documentation in one place might simplify cross-product usage - for example, [acra](https://www.cossacklabs.com/acra) users, who will want custom functionality from acra writer modules, will still need access to themis documentation, and if it's worth a few clicks instead of going to different site, it is going to save a lot of time, nerve and context switching

**Comment by gene-eu** [comment]
What would everyone say if we do it w/ [Jekyll](), which has plenty of themes that look like what we need: 
- https://github.com/CloudCannon/Aviator-Jekyll-Theme
- https://github.com/tomjohnson1492/documentation-theme-jekyll

Adding block layout from designs like this
- https://github.com/mmistakes/skinny-bones-jekyll

might make docs design more sophisticated and interesting.

**Comment by gene-eu** [comment]
On the other hand, we have plenty of people knowing Python and some people already did similar  things on Pelican (although we were not that happy with it).

**Comment by gene-eu** [comment]
Finally, we ended up needing a custom solution (docs management CMS of some kind), able to:
- custom page templates
- navigation pane with hierarchy
- in-page navigation tree autogenerated
- proper documentation search
- markdown editing

Some good examples: 
- https://stripe.com/docs
- https://www.librato.com/docs/api/ (language-specific pages!!)
- http://docs.basho.com/

**Comment by Lagovas** [comment]
- change history (with diffs)
- reverting changes
- interactive snippets

**Comment by Lagovas** [comment]
<img width="1767" alt="web_scheme" src="https://cloud.githubusercontent.com/assets/6237700/21521603/3d30a198-cd07-11e6-88d3-363021eb7187.png">

**Comment by Lagovas** [comment]
for history, one more example - https://tangerine-lemon.cloudvent.net/

**Comment by Lagovas** [comment]
@gene-eu releases from GH should be from all public repositories or only from themis (like on themis.cossacklabs.com)? the same question about commits/ci

**Comment by gene-eu** [comment]
custom list of reps

**Comment by Lagovas** [comment]
proposal 1: add a table of mapping words to pre-defined links like Secure Message to https://github.com/cossacklabs/themis/wiki/Secure-Message-cryptosystem and map them automatically during render MD to final output (via extended md syntax or something like that).
also, need to add an ability to decline mapping if some words appear in text many times or in some specific cases

proposal 2: add a table of named code snippets and extend md syntax where we could to reference via the name to these snippets that will be replaced by code blocks. it's should ease maintaining code snippets across texts

**Comment by gene-eu** [comment]
Awesome, do both

**Comment by gene-eu** [comment]
It really became a thing of it's own, planned and executed separately, closing this.
