### ISSUE TITLE
Compilation error of SwiftThemisServerExample

### ISSUE THREAD

**Issue by valeriyvan** [cossacklabs/themis#145]
Project can't be compiled and build because of compilation error in Themis itself:
./themis/docs/examples/Themis-server/swift/Pods/themis/src/soter/boringssl/soter_asym_cipher.c:146:8: Implicit declaration of function 'EVP_PKEY_get0_RSA' is invalid in C99

xcode 7.3.1

xcode 8 can't compile either because of old swift version of the project.

**Comment by vixentael** [comment]
Thank you!
I'll take a look

**Comment by valeriyvan** [comment]
Any news?

**Comment by vixentael** [comment]
not yet, but no worries, we're working on it

**Comment by vixentael** [comment]
Thank you, this was fixed by #147. 

All examples are working with the latest master now.
