### ISSUE TITLE
Update CircleCI tests: build iOS examples

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#152]
We missed it earlier, but we should update CircleCI tests to build iOS ObjC/Swift examples too.

It would prevent bugs iOS-specific linking bugs like #145

**Comment by vixentael** [comment]
Need to think about this. @mnaza says that CircleCi doesn't allow to have 2 test suites: both "linux" and "iOS" linked to one repo. So we can't run both linux/android and iOS tests on commit.

Maybe we can use some webhooks to workaround that behaviour?

**Comment by vixentael** [comment]
Thread discussing on @circle-ci about similar issue https://discuss.circleci.com/t/multiple-builds-for-one-repo/662/13

**Comment by vixentael** [comment]
how about switching to bitrise!

**Comment by gene-eu** [comment]
Need to discuss altogether - we'll have too many CIs (internal BuildBot (not used for Themis yet), Circle, now this one).

**Comment by vixentael** [comment]
Bitrise-Bitrise!

**Comment by vixentael** [comment]
bitrise setup looks working smooth for our scenario! 🎩

my next steps:

- [ ] update objc/swift tests in separate [/test](https://github.com/cossacklabs/themis/tree/master/tests) folder
- [ ] set up bitrise webhooks for automated tests on every push
- [ ] remove submodule (#154)
- [ ] enjoy

**Comment by vixentael** [comment]
Closed by #232, #231
