### ISSUE TITLE
Wrong repo for pod in submodule

### ISSUE THREAD

**Issue by valeriyvan** [cossacklabs/themis#154]
Why is Podfile in submodule set for different repo for themis???

**Comment by vixentael** [comment]
That's part of resolving Circle CI issues. You don't need to download submodule to use themis. Do you see any error while fetching repo?

**Comment by valeriyvan** [comment]
Forget about submodule.
xcode project at tests/objcthemis has pod for themis. But it's different themis! It's https://github.com/mnaza/themis.git, not current one.

**Comment by vixentael** [comment]
Thank you @valeriyvan. That's part of issue #152. Working on this.

**Comment by valeriyvan** [comment]
Won't `pod 'themis', :path => '../../themis.podspec'` in xcode project at tests/objcthemis solve that issue?

**Comment by vixentael** [comment]
It's not the issue of putting wrong podspec path :)  It's obviously wrong and will be changed later.

It was made intentionally while setup Circle-CI tests in past. However, Circle-CI is not working as expected

**Comment by valeriyvan** [comment]
At least we agree it's wrong)

**Comment by vixentael** [comment]
No one denied it is

**Comment by vixentael** [comment]
forget about boring gitsubmodules! new future is coming: testing using bitrise 💪

i'll remove submodule and close this issue when set up separate test workflow via bitrise #152

**Comment by vixentael** [comment]
Fixed, closed by #232, #231
