### ISSUE TITLE
Public function for getting id from connect request

### ISSUE THREAD

**Issue by Lagovas** [cossacklabs/themis#166]
Would be great add function that will parse id from connect request and return him. It's will be useful in secure session object initialization for loading private key for new client connection with specific id.
It will looks like (golang):
```
id := session.GetIdFromConnectionRequest(connection_request)
private_key := LoadPrivateKey(id)
secure_session := session.New([]byte("server_id"), private_key, &callback{})
```

**Comment by gene-eu** [comment]
Now we need to distribute it across the wrappers

**Comment by Lagovas** [comment]
actually, it is not what I meant *(
#202 allow getting peer id from an established secure session. but will be good if we allow to get peer id from connection request.
First packet from client to server is connection request which contains id of client. And then server can't fetch this id from this packet manually, only by hack like use callback for public key, call `session.Unwrap(connection_request)`, save passed `id` to callback somewhere, return error, ignore it and handle this case. And only after that can do something with this `id`...
