### ISSUE TITLE
ECDH - 

### ISSUE THREAD

**Issue by rustymagnet3000** [cossacklabs/themis#175]
How do I specify the named curve when generating a EC key pair using DH as the Key Agreement protocol?

**Comment by gene-eu** [comment]
Short answer is you can't :( 

The goal of Themis is to abstract cryptographic choices from user and provide him with cryptosystem we're confident is safe. 

We chose NIST P256 curve as main EC primitive for ECDH, and that has several reasons: 
- NIST curves fit many crypto compliance schemes
- Among classical ones, they're the most well studied, and NIST P256

We are well aware of Bernstein's view in [SafeCurves](https://safecurves.cr.yp.to/) work on P-256, but other named curves are studied even less and/or have more problems.

We plan to add ed22519 and/or ed449 in the nearest future, once we find simple and elegant solution to incorporate them into Themis cryptoprimitive architecture.

**Comment by rustymagnet3000** [comment]
Great answer.  Thanks for the detail.
