### ISSUE TITLE
make go wrapper compliant to 

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#176]
- godocs: godoc.org
- goreportcard.com
- coverage service link (gocover, coveralls etc.):

**Comment by gene-eu** [comment]
Andrey, figure this out and let us know whether we should do it.

**Comment by vixentael** [comment]
guys, @mnaza @gene-eu 

any progress here? should we care about this for 0.9.5 or should we postpone to 0.9.6?

**Comment by gene-eu** [comment]
it seems that test coverage is done, godoc is def 0.9.6, goreportcard - no idea

**Comment by Lagovas** [comment]
i looking how to attach coveralls to repo 
goreportcard.com we cant use, because it works only with pure go libraries and can't install custom libraries before check (we need install libthemis before running tests)

**Comment by Lagovas** [comment]
added calculating coveralls for gothemis but it can't be merged into themis coverage report (i saw it after first pushing coverage info for gothemis that coveralls doesn't merge it for one commit https://github.com/lemurheavy/coveralls-public/issues/613)
we can add the second badge only for gothemis (it checks separately from themis) and manually update badge link (gothemis rarely changes) or leave it at is and periodically manualy look at gothemis coverage when we touch this part of sources

**Comment by vixentael** [comment]
let's look manually on gothemis coverage for now

**Comment by vixentael** [comment]
Reopen, but postpone to 0.9.6 because `godoc is def 0.9.6`

**Comment by vixentael** [comment]
Together with @Lagovas we decided that there's nothing we can do here. Go code coverage is calculated, but we display code coverage for C only. We believe it is totally fine.
