### ISSUE TITLE
figure out how to integrate bernstein functions into soter

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#179]
goal: how can we integrate Bernstein algorithms/curves into Themis, keep on providing existing high-level API with existing guarantees. 

@secumod decides which algos/curves we need
@mnaza tries to implement

**Comment by gene-eu** [comment]
... consider ed448

**Comment by secumod** [comment]
I took a look into it for ed25519, since code is already integrated into Themis for SMP. One issue I could see now, that eddsa(25519 and probably 448) use deterministic signature generation, similar to the one described in [RFC 6979](https://tools.ietf.org/html/rfc6979). While this is great for security, in its current form it does not allow to compute signatures iteratively as data comes in (init, update, update... final), because you have to know the whole signed message in advance.

Since soter interface allows computing iterative signatures, I'm not sure how to proceed: should we try to adjust eddsa to support iterative signatures generating/verifying, which might break compatibility with other eddsa implementations or should we somehow abandon iterative interface in soter?

**Comment by mobrio** [comment]
Some thoughts (bearing mind I may not fully understand the problem) ...

The Init/N*Update/Final pattern clearly accommodates sources with sizes that exceed reasonable in memory operations. It might be convenient to wrap those 3 functions in a single function as for example the openssl `EVP_Digest` does with `EVP_DigestInit_ex`, `EVP_DigestUpdate` and `EVP_DigestFinal_ex` as a convenience for when source content fits comfortably in memory. [As an aside  note that the non "_ex" versions are documented as obsolete].

As I understand it for eddsa the message content **has** to pass through SHA-512 twice - once as part of generating a nonce and a second time as part of generating the signature. 

So to support arbitrary large messages 2 sets of Init/N*Update/Final calls are required  ... InitNonce/InitSign etc even though one might collapse the FinalNonce and InitSign into a single step ... thats getting a bit cumbersome tho its hard to imagine an alternative.

Equally if we suspect that in many cases messages to be signed fit comfortably in memory, then in my view we should be adding helper functions that wrap the Init/1*Update/Final calls (for eddsa there might be separate Updates 1x for elements that precede the message and 1x the message itself). 

I'm afraid the answer to the either/or question ... looks like being ... both :)

**Comment by gene-eu** [comment]
The situation is both better and worse from product-level perspective :) 

On higher (Themis) level, we always know the size of message. On Soter level, it's not so, but that's a minor risk - I don't think someone will embed Themis into their app to use only Soter, it's something even we do with great caution. 

Decision becomes problematic not because of the "right way": both are correct, and we might just end up having 2 now and then picking one which better covers more use-cases. However, there is Hermes, and the way Hermes utilizes things from Themis... is a bit different as I understand, and it actually is the most important consideration we have to keep in mind. I'd like to know (and it's something only @mnaza can tell us, apart from us going reading current version of **hermes-core**), will this decision affect the way Hermes works now, or, more importantly, in future?

**Comment by vixentael** [comment]
don't want to ruin your high level discussion here, but taking into account that Hermes is almost public, what are our next steps to solve this question?

**Comment by gene-eu** [comment]
it's in a separate branch as well, article is prepared, necessary changes in soter were applied long time ago, @mnaza just forgot to update things here, I guess

**Comment by vixentael** [comment]
Status update. 
In fact, situation is the same as solving this issue https://github.com/cossacklabs/themis/issues/184


Status update (based on @mnaza input).

Changes are sitting here
https://github.com/mnaza/themis/tree/libsodium

Merge plan:
 
- [ ] Merge this branch into your own fork.

- [ ] **Fix Keygen Interfaces** 
  Check key generation functions, they are changed from two functions
     `themis_gen_ec_key_pair(...)` and `themis_gen_rsa_key_pair(...)`
     to one `themis_gen_key_pair(THEMIS_SECURE_ENCRYPTED_MESSAGE_DEFAULT_ALG|THEMIS_SECURE_SIGNED_MESSAGE_DEFAULT_ALG, ...)`
   - [ ] Make sure that `themis_gen_ec_key_pair(...)` and `themis_gen_rsa_key_pair(...)` are working correctly using new key_gen function (backward compatibility).
   - [ ] Make sure that *all* Themis wrappers are building/working correctly through old functions.

 - [ ] **Handle Infrastructure issues**
   Currently we don't have any way to change 'backend providers' (OpenSSL/LibreSSL/BoringSSL/BearSSL/LIBSODIUM). In fact, this switch is possible from C-core only, wrappers don't have this feature. 
   Our goal is to create simple "switcher" that allows to switch from different backend providers. Question: how to handle dependencies (for example, iOS wrapper is linked to OpenSSL directly through podspec). 
   Creating `./configure` script might be an option.

   - [ ] Create switcher from one backend provider to another, allow wrappers to use different backend providers.

- **Update and Fix Tests** 
Merge tests with tests from base branch, check that tests are running successfully. Careful, CircleCI build usually takes ~30min
   - [ ] Make sure that *all* Themis wrappers are building/working correctly

**Comment by gene-eu** [comment]
as discussed with @mnaza, @vixentael: this barely adds any value for users in 0.9.5, so should be kept in a separate branch to illustrate research articles and that's it. When we have time after H/T releases, we'll definitely revisit ways for one build process for different backends, but it isn't worth it right now.
