### ISSUE TITLE
Distribute SComparator docs across all wrapper docs

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#182]
... the way it's described in Python now.

**Comment by vixentael** [comment]
@karenswry is there any progress with SComparator docs?

**Comment by vixentael** [comment]
Would be cool to have it, TBH

**Comment by vixentael** [comment]
Almost done.

Handy checklist:

- [x] objc
- [x] swift
- [x] android / java
- [x] ruby
- [x] go
- [x] nodejs
- [ ] cpp

PHP wrapper does not support Secure Comparator yet.

**Comment by vixentael** [comment]
Done 🎆
