### ISSUE TITLE
Python HowTo doesn't follow PEP8

### ISSUE THREAD

**Issue by pahaz** [cossacklabs/themis#185]
https://github.com/cossacklabs/themis/wiki/Python-Howto

I'm a Python developer and for me It's looks ugly. 
PEP8 is a Python code style standard. 
We don't use CamelCase for class names. 
Just remove the `;` at the and of examples.

```
     while !(session.is_established():
       session.receive();
```

IS IT REALLY PYTHON?

> BEST PRACTICE: Themis is based on best modern practices in implementing complicated security systems.

Are you sure?

Sorry for this issues, but if you really want to make a usable solution, you need to correct the style.

**Comment by gene-eu** [comment]
Thank you for your feedback! This will be fixed really soon. Truly, this does not look like good Python code, and will be fixed quite soon. As I can see, @Lagovas, our main internal PEP evangelist, has already picked up the task for himself :) 

>>BEST PRACTICE: Themis is based on best modern practices in implementing complicated security systems.
>Are you sure?

We were referring the security practices, which are crucial for such product. Unfortunately, being focused on security/engineering part of it sometimes makes us myopic in usability/style aspects of high-level wrappers.

**Comment by gene-eu** [comment]
It would be fair to ask @pahaz, whether the fixes fit hit expectations of style before closing :)

**Comment by gene-eu** [comment]
well, it has been now sitting this way long enough for anyone to object
