### ISSUE TITLE
Add notes to docs about scell context imprint and smessage ssign/verify

### ISSUE THREAD

**Issue by Lagovas** [cossacklabs/themis#186]
1. add note to docs about non-error decrypting in scell context imprint mode without errors. Token protect and seal modes return error if can't decrypt, context imprint mode return corrupted data without any signals about error. I think it should be noted for users who doesn't know that it's ok for block ciphers

2. add note that smessage sverify doesn't signal about appending data to end of block and return correct signed data from start of block, excluding incorrect data at the end. but check and signal about error when incorrect data appended to start of block

**Comment by Lagovas** [comment]
2. @mnaza said that maybe will add check of whole block of data and sverify will return some error code

**Comment by vixentael** [comment]
any progress here?

@Lagovas can you please review this issue and write if there's anything to do

**Comment by Lagovas** [comment]
didn't see any comments related to this issue so now we just need to add notes to docs 
i think we should move this issue to next release if we want to add these checks

**Comment by vixentael** [comment]
Docs updated.

We will consider updating `sverify` behavior to check data on the end of the message (next or next-next release).
