### ISSUE TITLE
Create Integration Test suit for wrappers

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#192]
> If the same tests are repeated over and over again, eventually the same set of test cases will no longer find any new defects. To overcome this “pesticide paradox”, test cases need to be regularly reviewed and revised, and new and different tests need to be written to exercise different parts of the software or system to find potentially more defects

I think it would be valuable to discuss tests for 0.9.5, given recent challenges we've encountered with Themis in different environments. Current test coverage is fine for crypto part, but integration part could be covered a bit better, innit?

**Comment by vixentael** [comment]
agree, but it looks like we won't make it for 0.9.5, rather move to 0.9.6

**Comment by gene-eu** [comment]
definitely

**Comment by vixentael** [comment]
start working on integration tests

#260

**Comment by vixentael** [comment]
Almost done!

Integration test suit is created and put into [`tests/_integration`](https://github.com/cossacklabs/themis/tree/master/tests/_integration) folder.
We support integration testing for Secure Cell and Secure Message modes between Go, Ruby, Python, Js and PHP wrappers. 

Related PRs: #294  #293 #291 #289  #285  #284  #281

**Bonus:** now you can use console utils for local testing on your machine! 

Handy console programs are placed into [`tools`](https://github.com/cossacklabs/themis/tree/master/tools) folder separately for each wrapper.

We will run these tests automatically on circle CI and buildbot.
