### ISSUE TITLE
Can Themis be used from a Swift project on Linux?

### ISSUE THREAD

**Issue by popaaaandrei** [cossacklabs/themis#198]
Hello,

Can anyone tried integrating Themis library in a Swift project on Linux?
Theoretically it should work by creating a module map around the C++ library but has anyone succeeded?

I want to exchange data securely between iOS and a Vapor backend deployed on Ubuntu.

Thank you!

**Comment by vixentael** [comment]
Well, Themis works on Linux, and Themis works on iOS Swift via ObjC bridging headers. I believe there shouldn't be any issues that prevent Themis to work directly in Swift projects :)

If you have any experience in building module map around C core, could you help us? Our Linux-gur @mnaza can help with any core-related issues.

**Comment by mnaza** [comment]
TR;DL; Yes. Themis can be used from a Swift project on Linux
I newer before use Swift, but decide to try:
1. create package for Themis (I call it CThemis):
```
mkdir CThemis
cd CThemis
echo "module CThemis [system] {
    header \"/usr/include/themis/themis.h\"
    link \"themis\"
    export *
}" > module.modulemap
cd -
```
2.  for key pair generation with temis create file `main.swift` with next context:
```
import CThemis

var res: Int32
var private_key_length: Int = 0
var public_key_length: Int = 0

// private and public keys length determination
res = themis_gen_ec_key_pair(nil, &private_key_length, nil, &public_key_length)
if res != SOTER_BUFFER_TOO_SMALL {
    print("private & public keys length determination error")
    exit(-1)
}

// private and public key memory allocation
var private_key = [UInt8](repeating: 0, count: private_key_length)
var public_key = [UInt8](repeating: 0, count: public_key_length)

// private and public keys generation
res = themis_gen_ec_key_pair(UnsafeMutablePointer(mutating: private_key), &private_key_length, UnsafeMutablePointer(mutating: public_key), &public_key_length)
if res != SOTER_SUCCESS {
    print("private & public keys generation error")
    exit(-1)
}

//result output
print(private_key, private_key_length)
print(private_key, private_key_length)
```
3. build app with
```
swiftc -I ./CThemis main.swift
```
4. run:
```
./main
```
all other Themis functions can be imported to Swift by same way.

**Comment by vixentael** [comment]
Thank you, @mnaza!

I think we should consider building "pure Swift" wrapper for those who use Swift on server.

**Comment by popaaaandrei** [comment]
Thank you, @mnaza Really appreciate your effort 👍

**Comment by gene-eu** [comment]
@mnaza, it feels like @popaaaandrei will need to know some internals to succeed in his goal (e.g. understanding the sequence of C Themis calls to get correct results). If you've went the most of the way already, maybe you can invest a few minutes to draft out the rest of the functions?

Style-inferiority and "Swift-ness" is something @vixentael and @popaaaandrei (if he wants to) can easily correct, but if @popaaaandrei's goal is to use "secure data exchange", that's Secure Session, and it may be not very trivial to write a wrapper for it without really good understanding of how it works. 

Maybe you could invest some more time on this and push this to /wrappers/?

**Comment by popaaaandrei** [comment]
Thank you all for support!
I can help with Swift-ness :) My goal is to send encrypted data from the hospital (Swift on Ubuntu) to the patients (iOS and Android) based on public key crypto and I think Secure Message is would fit perfectly. Secure Session seems like too much for what I need.

**Comment by popaaaandrei** [comment]
@gene-eu @mnaza  I made a wrapper for Secure Message using your code and ObjC wrappers as a reference.

**Comment by vixentael** [comment]
wow, can you share it please @popaaaandrei

**Comment by popaaaandrei** [comment]
[CThemis.zip](https://github.com/cossacklabs/themis/files/1032027/CThemis.zip)
[test.zip](https://github.com/cossacklabs/themis/files/1032034/test.zip)

First is the C module required. Second is a test project with key generation and encryption + decryption.

Thank you all!

**Comment by popaaaandrei** [comment]
I didn't know how to suppress the `... was never mutated, consider changing to 'let'`. I am a little concerned with changing to `let` while using `UnsafeMutablePointer(mutating: ...)`

**Comment by mnaza** [comment]
I create Themis wrapper for Swift for Linux for all Themis primities (except Secure Comparator, for now):
[modulemap](https://github.com/cossacklabs.com/SwiftCThemis)
[wrapper](https://github/cossacklabs/SwiftThemis)

@popaaaandrei , @vixentael , check it please.

Note: [wrapper](https://github/cossacklabs/SwiftThemis) include `examples` folder with example project. Before use it, [Themis](https://github.com/cossacklabs/themis) must be installed with: `make install`

**Comment by gene-eu** [comment]
... it would be great when you finish polishing this, come up with distribution scheme that doesn't involve 3 repos, and document things properly ;)

**Comment by popaaaandrei** [comment]
I can only confirm that Secure Message (both modes encrypt/decrypt and sign/verify) works for me bi-directionally between an Ubuntu endpoint and an iOS app. Thank you @mnaza

**Comment by gene-eu** [comment]
>I can only confirm that Secure Message (both modes encrypt/decrypt and sign/verify) works for me bi-directionally between an Ubuntu endpoint and an iOS app.

Great to hear! 

(my inquiry above was obviously direted towards @mnaza :) )

**Comment by vixentael** [comment]
Thank you guys, I've separated issue about making Swift Themis better into separate issue (#226)
