### ISSUE TITLE
distribute secure_session_get_remote_id across all wrappers

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#203]

**Comment by vixentael** [comment]
any progress here? is it already implemented? @mnaza 

should we do it for 0.9.5 or change milestone to 0.9.6? @gene-eu

**Comment by gene-eu** [comment]
I'm not sure if it's in every wrapper, only in those necessary for Hermes / Acra.

**Comment by vixentael** [comment]
current state is unclear. should review.

**Comment by Lagovas** [comment]
state after merging #272
- [x] gothemis
- [ ] pythemis
- [ ] rubythemis
- [ ] jsthemis
- [ ] phpthemis

**Comment by vixentael** [comment]
I have a feeling that we've done here a but, but no further public updates are planned, so I close this issue.
