### ISSUE TITLE
Compile error in iOS

### ISSUE THREAD

**Issue by ys1382** [cossacklabs/themis#206]
Many errors with the text "Include of non-modular header". For example,

Pods/themis/src/themis/message.h:20:10: Include of non-modular header inside framework module 'themis.message':

Compiling with Xcode 8.3.2

**Comment by vixentael** [comment]
Thank u @ys1382

I'll take a look

**Comment by vixentael** [comment]
I can confirm that themis 0.9.4 is working for both objc and swift wrappers on xcode 8.3.3 and current 9-beta.

@ys1382 could you please specify what version of themis are using?

**Comment by vixentael** [comment]
However, I've updated example to link explicitly to the 0.9.4 stable release.

@ys1382 could you please try building iOS example again? thank u

**Comment by vixentael** [comment]
Hi @ys1382, any updates?

**Comment by ys1382** [comment]
Yes it compiled on iOS now, thanks.
