### ISSUE TITLE
Themis doesn't build on debian 9 with openssl 1.1.0f

### ISSUE THREAD

**Issue by Lagovas** [cossacklabs/themis#208]

**Comment by mnaza** [comment]
As a temporary solution: to build themis on debian 9, install `libssl1.0-dev` instead `libssl-dev`

**Comment by vixentael** [comment]
guys, let's move to 0.9.6 :)

**Comment by gene-eu** [comment]
agreed :( but let's not delay this for too long.

**Comment by Lagovas** [comment]
#258
