### ISSUE TITLE
Swift example connect

### ISSUE THREAD

**Issue by ys1382** [cossacklabs/themis#212]
I followed the Swift documentation to create a TSSessionTransportInterface and TSSession. To initiate the handshake, do I:
1) call "let data = session.connectRequest()" and then send the data?
2) call session.connect() and wait for a callback to tell me to send data?

When connection request data arrives at the peer, how do I give it to the session object? By calling unwrap?

The Swift example code doesn't use any of these APIs.

Let me know if I should be asking these questions in some other forum.

**Comment by gene-eu** [comment]
@ys1382, this is perfect place to ask, as soon as anyone who talks Swift will notice this issue, they'll pick it up (@vixentael, @mnaza?).

**Comment by vixentael** [comment]
Hi @ys1382 

Please refer to this example for Themis Secure Session on Swift2

https://github.com/cossacklabs/theswiftalpsdemo#transfer-encryption-example

It contains SecureSession client and server code, together with some explanations.

-----------------------

Step-by-step guide

1. Define `class Transport: TSSessionTransportInterface` that stores server public key. Please add overriden function `override func publicKey(for binaryId: Data!) throws -> Data` that selects public key based on server Id

https://github.com/cossacklabs/theswiftalpsdemo/blob/master/ios-project/SwiftAlpsSecDemo/SwiftAlpsSecDemo/SessionDemo.swift#L13  

2. Initialize Transport with server Id and public key

``` swift
self.transport = Transport()
self.transport?.setupKeys(serverId, serverPublicKey: serverPublicKey)
```

https://github.com/cossacklabs/theswiftalpsdemo/blob/master/ios-project/SwiftAlpsSecDemo/SwiftAlpsSecDemo/SessionDemo.swift#L114

3. Initialize Secure Session

```swift
self.session = TSSession(userId: clientIdData, privateKey: clientPrivateKeyData, callbacks: self.transport)
``` 

https://github.com/cossacklabs/theswiftalpsdemo/blob/master/ios-project/SwiftAlpsSecDemo/SwiftAlpsSecDemo/SessionDemo.swift#L116

4. Create connection message

```swift
let resultOfConnectionRequest = try session?.connectRequest()
```

https://github.com/cossacklabs/theswiftalpsdemo/blob/master/ios-project/SwiftAlpsSecDemo/SwiftAlpsSecDemo/SessionDemo.swift#L119

5. Post connection message to start session

```swift
self.startSession(clientId: clientId, message: connectionMessage, completion: {...} 
```

6. Check callback to sure that session is established

```swift
session.isSessionEstablished()
``` 

https://github.com/cossacklabs/theswiftalpsdemo/blob/master/ios-project/SwiftAlpsSecDemo/SwiftAlpsSecDemo/SessionDemo.swift#L171

7. Then send encrypted payload message

```swift
encryptAndSendPayload(message: messageToSend, clientId: clientId, completion: { ... }
```

https://github.com/cossacklabs/theswiftalpsdemo/blob/master/ios-project/SwiftAlpsSecDemo/SwiftAlpsSecDemo/SessionDemo.swift#L140

----------------------

I will update this example on Swift3 (or 4?) in nearest time.

You may also be interested in Objective-C SecureSession example from this guide
https://github.com/cossacklabs/mobile-websocket-example

**Comment by vixentael** [comment]
Another simple way to play with SecureSession is to use Themis server Swift3 example: [/docs/examples/Themis-server/swift](https://github.com/cossacklabs/themis/tree/master/docs/examples/Themis-server/swift)

Basically, example provides clients code on Swift and you don't need to start your own server to test it, you can play with [Themis Interactive simulator](https://github.com/cossacklabs/themis/wiki/Using-Themis-Server) instead.


Please, follow the [README](https://github.com/cossacklabs/themis/tree/master/docs/examples/Themis-server/swift) to start.

**Comment by ys1382** [comment]
Thanks, those examples are helpful to understand the flow. But when I run them, Themis-server/swift gives this output:

> Oops, response = <NSHTTPURLResponse: 0x61000002f660> { URL:
> https://themis.cossacklabs.com/api/hAxNatMbDDbNUge/ } { status code: 404, headers {
> Connection = "keep-alive";
>    "Content-Length" = 84;
>    "Content-Type" = "text/plain; charset=utf-8";
>    Date = "Tue, 04 Jul 2017 01:43:51 GMT";
>    Server = "nginx/1.6.2";
> } }

And when I run I SwiftAlpsSecDemo, I get this output:

> 💥 Error occurred while decrypting session start message Error
> Domain=com.CossackLabs.Themis.ErrorDomain Code=-6 "Secure Session failed decryption"
> UserInfo={NSLocalizedDescription=Secure Session failed decryption}
> startSession(clientId:message:completion:)
>💥 Error occurred while session initialization Optional(Error
> Domain=com.CossackLabs.Themis.ErrorDomain Code=-6 "Secure Session failed decryption"
> UserInfo={NSLocalizedDescription=Secure Session failed decryption})
> sendPayload(serverId:serverPublicKey:clientId:clientPrivateKey:messageToSend:)

**Comment by vixentael** [comment]
Basically, it means that client and/or server is wrong configured :)
Important step of SecureSession is building trust between client and server, basically it means to use correct keys on both ends.

Let's continue our discussion based on Themis Server Swift example.

I've updated [README](https://github.com/cossacklabs/themis/tree/master/docs/examples/Themis-server/swift), trying to make it more descriptive (also added pics!). Please, try to follow step by step guide and let me know if some steps are unclear.

**Comment by ys1382** [comment]
I got end to end working here: https://github.com/ys1382/gochat/tree/master/apple
