### ISSUE TITLE
Compile issue on OSX

### ISSUE THREAD

**Issue by ys1382** [cossacklabs/themis#214]
I am using Themis in Android, and I followed the instructions [here](https://github.com/cossacklabs/themis/wiki/Building-and-installing), I get this result when I type `make install`:

> src/soter/openssl/soter_engine.h:21:10: fatal error: 'openssl/evp.h' file not found

**Comment by secumod** [comment]
We have Android-specific instructions: https://github.com/cossacklabs/themis/wiki/Java-and-Android-Howto#building-themis-for-android

Can you try them instead?

**Comment by ys1382** [comment]
Thanks, thought the other step was required first. When I only run `./gradlew build`, I get this error:

> /Users/moi/themis/jni/Android.mk:20: *** "boringSSL path must be set".  Stop.
> :ndkBuild FAILED

**Comment by secumod** [comment]
Right... We used to have embedded OpenSSL for Android builds, but recently moved Themis to use BoringSSL. This is inline with the AOSP project, where newer Android versions also use BoringSSL. I guess, we need to update Android instructions to reflect this.

But in the meantime, you can try to follow the steps we use in CI:
1. Build BoringSSL for Android: https://github.com/cossacklabs/themis/blob/master/circle.yml#L22-L25
2. Build Themis with BoringSSL: `./gradlew --info -Pboringssl_path=$HOME/boringssl build`

You might have to install some tools from the list in https://github.com/cossacklabs/themis/blob/master/circle.yml#L9, notably `cmake`, `build-essential`, `ninja-build`.

**Comment by gene-eu** [comment]
>I guess, we need to update Android instructions to reflect this.

@karenswry, would you please update the docs in the meanwhile.

**Comment by karenswry** [comment]
Documentation updated with BoringSSL-related instructions for Android.

**Comment by ys1382** [comment]
Thanks, I could build and integrate BoringSSL.

**Comment by vixentael** [comment]
Hi again @ys1382  :)

Sorry for disturbing, but I'm preparing a post on Cossack Labs web site to thank contributors and mention projects that use Themis. Don't you mind I ask you a for details of your project?
Unfortunately I don't know you email, could you please ping me at vixentael@gmail.com?
