### ISSUE TITLE
Come up with better distribution scheme for Swift Themis on Linux

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#226]
As result of this issue (https://github.com/cossacklabs/themis/issues/198) we can be sure that Themis is working on Linux.

@mnaza has created separate repos for it
https://github.com/cossacklabs/themis/issues/198#issuecomment-304508661

We should re-think how to integrate Themis Linux into main repo OR how to make it more usable (including writing docs).

No detailed plan yet, but this issue will be our reminder!

**Comment by gene-eu** [comment]
Until the first adopter comes up swinging

**Comment by vixentael** [comment]
No further public updates are planned, so I close this issue. @popaaaandrei had Swift Themis working using similar repo approach, as we previously tried (separate repos for [SwiftCThemis](https://github.com/cossacklabs/SwiftCThemis) and [SwiftThemis](https://github.com/cossacklabs/SwiftThemis)).

If more users will ask for this, we'll consider (any help appreciated!).

**Comment by ksinghal** [comment]
Hi, this capability would be very useful to me, and I would be happy to help implement it

**Comment by vixentael** [comment]
Hi @ksinghal! Feel free to contribute!
As I've mentioned in a previous comment, there was a working solution that required two separate repositories. We tried it, another user used it. Maybe current progress with Swift on server made distribution easier.

Recently, we've added support of SPM for Themis-iOS and macOS, so if it's possible to use SPM approach for swift on server, it might make sense.
