### ISSUE TITLE
Consider docker as a build system for Themis

### ISSUE THREAD

**Issue by secumod** [cossacklabs/themis#233]
Docker is a popular, clear an easy way to distribute environments. How about making preconfigured images to make it easier to build Themis for less obvious platforms, which require a lot of steps to set up the build environment, like Android?

**Comment by vixentael** [comment]
Upd:
thank to @secumod now we can build Themis Android using docker.

Corresponded wiki instruction can be found here
https://github.com/cossacklabs/themis/wiki/Java-and-Android-Howto#quick-start-using-docker

**Comment by secumod** [comment]
I'm now trying to migrate Themis to Circle CI v2.0 configs. v2.0 allows you to specify custom Docker images for running your test-suite, so I'm using `cossacklabs/android-build` for that, so most likely, when I'm done, that image can be used to build almost all Themis variants, excluding esoteric platforms, like Mac OS ;)

**Comment by vixentael** [comment]
Thank you @secumod! Now when migration to Circle CI 2.0 is complete and we're using same docker image for building Themis, we shall think how to describe users that they can use docker image now.

**Comment by vixentael** [comment]
Well, it's kinda done and working.
Need to add "usage" line to the docs.

**Comment by Rasie1** [comment]
@vixentael Wiki is moved away from github and there seems to be no corresponding page on docs.cossacklabs.com. I'll now try `cossacklabs/android-build` which I found here, but complete guide could be probably useful, because searching `docker` on docs site returns results only for Acra

**Comment by vixentael** [comment]
hi @Rasie1! you are right, no wiki on github anymore, all themis docs are at https://docs.cossacklabs.com/themis/ (the content is open source [here](https://github.com/cossacklabs/product-docs)).

You don't need Docker to use Themis. Themis is a library and could be installed from package managers on every supported platform:
https://docs.cossacklabs.com/themis/installation/

To make our CI tests easier, we support own docker files where we pre-install dependencies typically used in Themis tests: https://github.com/cossacklabs/dockerfiles, including a special `cossacklabs/android-build` which simplifies building Themis on Android with BoringSSL.

The flow is described in Themis Android docs [Languages > Kotlin > Installation Android > Using Docker](https://docs.cossacklabs.com/themis/languages/kotlin/installation-android/#using-docker). However, using this docker file is rather an edge case: to build Themis from sources on our CI or to manual install Themis Android for those developers who couldn't install it [from Gradle](https://docs.cossacklabs.com/themis/languages/kotlin/installation-android/#installing-stable-version-with-gradle).

If you are looking how to install Themis on Docker – just follow typical [Installation from package guides](https://docs.cossacklabs.com/themis/installation/#installing-themis-from-packages).

As everyone uses Themis differently, we can't predict which OS you'd prefer, which other libraries you'd like, so we don't provide any ready-made Docker files.

If you are looking for an inspiration, these are [Themis CircleCI workflows](https://github.com/cossacklabs/themis/blob/master/.github/workflows/test-nodejs.yaml#L26) that basically install all dependencies based on `ubuntu-latest` Docker.
