### ISSUE TITLE
Review build instructions for Java/Android

### ISSUE THREAD

**Issue by secumod** [cossacklabs/themis#235]
There have been some changes in the way how JDK (at least on Linux systems) is structured. Some steps on the Wiki might need to be updated.

**Comment by vixentael** [comment]
@secumod would be great if you could take a look till October 18 :)

**Comment by vixentael** [comment]
Currently building and installing Themis for Android looks rather exhausted. Users should compile BoringSSL for several architectures, do magic tricks with libs (copy libs to same folder), then run gradle script to get .aar files.

Maybe there is a better approach 🤔

**Comment by vixentael** [comment]
Need halp

**Comment by vixentael** [comment]
Thank you @secumod!
I think this issue is fixed by your latest PR and wiki update. Docker image for Android is a blast!
