### ISSUE TITLE
Do not use 'themis' name in cocoapod subspec

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#25]
Currently `themis.podspec` contains subspec named "themis". 

It leads to multiple search results, when user is looking for themis in CocoaPods repo:
![screen shot 2015-06-02 at 17 53 00](https://cloud.githubusercontent.com/assets/2877920/7938839/3cd035c8-0950-11e5-853b-a3f2b471042d.png)

Historically, such naming had sense while we were solving the problem with the folder structure. 

But now I suggest renaming subspecs to `core` and `objcwrapper`, if it won't break folder structure:

```
    s.subspec 'core' do |ss|
       ...
    end    
    s.subspec 'objcwrapper' do |ss|
       ...
    end
```

**Comment by mnaza** [comment]
Why not, If it won`t break folder structure.
