### ISSUE TITLE
Fix C coding style

### ISSUE THREAD

**Issue by secumod** [cossacklabs/themis#270]
Many of Themis `.c` files have different code style (or no code style at all?). This creates confusion for potential contributors. Let's fix one coding style for all Themis/soter (not imported) `.c` files. My proposal is to use [clang-format](https://clang.llvm.org/docs/ClangFormat.html) tool:
  * discuss and select initial coding style
  * fix it by writing a `.clang-format` and commit it to the repository
  * format Themis `.c` files with it
  * maybe, create a Makefile target, which developers can call to format all Themis/soter sources (in case they add additional files in the future)
  * finally, integrate format validation in CI (basically, fail the CI if code is not properly formatted) to enforce proper coding style for contributions

**Comment by vixentael** [comment]
I think it's a great idea. I think we should try to format using LLVM or Google pre-defined styles first, just to understand how far we are from their code style, then to apply @secumod step-by-step :)

**Comment by secumod** [comment]
In `clang-format` you can inherit the style and just override parameters you need - that's the best approach IMO. For example, you can define in your `.clang-format` you're using `llvm` style as a baseline, but override ident width (they use 2, but I like 4 for example).

**Comment by secumod** [comment]
Generally I'm fine with `llvm` style, just generally prefer `IndentWidth` to be 4. However, I'll not fight for it, because sometimes 2 is handy: when you have multilevel nested code, you generally have more room for nested levels.

**Comment by gene-eu** [comment]
Awesome idea. It's important to investigate the volume of effort to achieve that to prioritize this along other goals we've got for next release. Asking @vixentael or @Lagovas to weigh in with well-investigated opinion on how long will it take to do this.

**Comment by Lagovas** [comment]
never worked with this utility and doesn't know how they will work with current code formatting. it can be like one-time run and forget, or run and fix in many places bad readable formatting. if we have time then it will be good. if not, then it's good to start to use it incrementally on changed files in commit

**Comment by secumod** [comment]
Actually the readability is OK. I just encountered that I needed to refactor includes in main `themis.h` header: the problem was if includes are grouped together without extra newlines, `clang-format` sorts them. In our case, it have put `themis_errors.h` last, so the compiler failed when parsing other headers, because it could not find `themis_status_t` definition.

Fixed it by moving `themis_error.h` higher and adding a newline.

For complete example, see this branch: https://github.com/secumod/themis/tree/clang-format/src/themis

I reformatted files in `src/themis` with `clang-format` default `llvm` style.
It did not break the build it seems: https://circleci.com/gh/secumod/themis/50

**Comment by Lagovas** [comment]
vote for pointer on type instead variable name :) (`int* a` instead `int *a`)
exception is case with many variables like `int *a, *b, *c;`
but I think it will be too complicated for automated tool :(
I see you are formatted themis sources and it's great anyway :+1:

**Comment by secumod** [comment]
See `PointerAlignment` in https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by ilammy** [comment]
🎉 Y—A—A—A—A—Y 🎉 

Now the code style is updated and enforced for the core Soter and Themis libraries. Other C sources are still in disarray, but we'll sort that out. Eventually.

@gene-eu:

> how long will it take to do this

Four days. For what could have been a simple `clang fmt` with no effort, if there was only one vendor of C compilers in the world... Well, at least we have this point covered for now.
