### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [cossacklabs/themis#275]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by vixentael** [comment]
Thank you, @ZaMaZaN4iK 
We will consider this for the future release

**Comment by vixentael** [comment]
I'm closing this issue for now. 
We will consider supporting Conan when users request it, however you are most welcome to create a Conan package.
Thank you
