### ISSUE TITLE
Generating public key from existing (imported) private key

### ISSUE THREAD

**Issue by sigmundfridge** [cossacklabs/themis#313]
There are examples for importing a private key from a text file, but is there a way to use this to generate a new public key?

**Comment by vixentael** [comment]
If you're using  RSA and you have your private key stored in `myprivatekey.pem`, you can generate a public key using

```
openssl rsa -in myprivatekey.pem -pubout > mykey.pub
```


Themis doesn't provide a function to generate public key from private, but it allows you to generate a keypair. 

For example, for [ObjC it looks like](https://github.com/cossacklabs/themis/wiki/Objective-C-Howto#keypair-generation-interface):

```
TSKeyGen * keygenRSA = [[TSKeyGen alloc] initWithAlgorithm:TSKeyGenAsymmetricAlgorithmRSA];
NSData * privateKey = keygenRSA.privateKey;
NSData * publicKey = keygenRSA.publicKey;
```

[for PHP](https://github.com/cossacklabs/themis/wiki/PHP-Howto#keypair-generation-interface):
```
$keys = phpthemis_gen_rsa_key_pair();
if ($keys !== NULL) {
	$private_key = $keys['private_key'];
	$public_key  = $keys['public_key'];
}
```

**Comment by sigmundfridge** [comment]
OK thanks. Unfortunately, I'm trying to do this inside of the app rather than command line (essentially an action similar to SecKeyCopyPublicKey)

**Comment by vixentael** [comment]
Ah I see. Unfortunately we don't have this kind of API in Themis, we even didn't consider that this might be useful.

Could you please describe a bit your use-case? What kind of app are you creating? Is it just a one-time need, or it's typical for your use-case to store private keys and generate public keys from them instead of storing a whole key-pair?

We will consider adding this API to the next version of Themis, if many people are using it.

**Comment by sigmundfridge** [comment]
Potentially a very specific use case. It's for end to end encryption (so the user is the only person who can decrypt their own data). Users can save their private key as a mnemonic (to be written down and stored somewhere safe) so they have a back up in case of changing device/deleting app. Entering mnemonic recreates the private key, and I had hoped to create a new public key from that. Potentially I'll just have to make the mnemonic backup the whole key pair.

**Comment by vixentael** [comment]
Maybe you can encrypt the key-pair into symmetric container (using Secure Cell, for example), and store it elsewhere. Users will enter mnemonic that recreates symmetric key, that is used to decrypt key-pair.
