### ISSUE TITLE
Not Able to Compile and Install the themis in windows for Java.

### ISSUE THREAD

**Issue by sourabhlodha** [cossacklabs/themis#316]
I have:
Read the documentation and follow the same step but not able to install the themis in windows system for Java Version.

Kindly provide me the solution ASAP

Thanks
Sourabh Lodha

**Comment by karenswry** [comment]
Hello, Sourabh!
For us to be able to help you, please fill in the **issue template below**  (you saw it when opening the Issue) with the details about your system and the exact issues you're having.

Thank you
Karen.

----------------------------------------

### **Issue template:**
I have:

- [ ] searched open and closed issues for duplicates

----------------------------------------

### Issue description
Describe here the issue that you are experiencing.

### Environment info

**OS:** OS name and version

**Themis version:** 0.0.0

**Installation way:**
 - [ ] downloaded tag from github
 - [ ] via package manager
 - [ ] built from source

**Crypto provider:** OpenSSL / BoringSSL / LibreSSL (v0.0.0)

### Link to the example project

. . .

**Comment by sourabhlodha** [comment]
Hello @karenswry 

I have searched from open and closed issues for duplicates.

I am not able to install this on windows10 os.I want to use this library in Java For Encryption and decryption.

Environment info
OS:Windows 10
Themis version :Latest download from github
Installation way
Downloaded tag from github
Crypto Provider:OpenSSL

Link to project:
Used the Example present in repoitory.

**Comment by sourabhlodha** [comment]
@karenswry 

While I am running the jni code. I am facing the error in Line 
System.loadLibrary("themis jni"); //Not Able to find the themis jni.

Can you guide me how to fix this issue? Even While I compile in Ubuntu Xenial.I get the build with this libsoter.so,libthemis.so,libthemis.a.

Regards
Sourabh Lodha

**Comment by vixentael** [comment]
@sourabhlodha 
please provide steps you are doing and exact error messages you have.

This error means that jni was not built
> System.loadLibrary("themis jni"); //Not Able to find the themis jni.

Have you done `make themis_jni` step described in [Java and Android Howto](https://github.com/cossacklabs/themis/wiki/Java-and-Android-Howto#building-themis-for-java)?

**Comment by sourabhlodha** [comment]
@vixentael 
Steps to be followed:-
1.Make Install //It will generate the build 

After that I used the jni example to run the code but got the exception
com.cossacklabs.themis.KeypairGenerator.generateKeys(I)[[B

Can you guide me how to run a themis with simple example.

Thanks 
Sourabh Lodha

**Comment by sourabhlodha** [comment]
@vixentael 

I tried with set the path of build files in java but facing same error 
 no themis_jni in java.library.path

**Comment by vixentael** [comment]
@sourabhlodha 

Can you please check if you call `make themis_jni`?

Step by step guide for Java and Android described below
https://github.com/cossacklabs/themis/wiki/Java-and-Android-Howto#building-themis-for-java

**Comment by sourabhlodha** [comment]
@vixentael 

I can use this command and it will create libthemis_jni.so but not able to use in java project.

**Comment by sourabhlodha** [comment]
@karenswry 
I install the openSSL and then clone the git repository.After that I run the command make themis_jni and it will build the project and I get the file of libthemis_jni.so,libsorter.a ,libthemis.a and obj.

After that I create a simple java project and copy all files from here 
https://github.com/cossacklabs/themis/tree/master/src/wrappers/themis/java/com/cossacklabs/themis

Then create a main class
In Main Method 
Keypair pair = KeypairGenerator.generateKeypair();
		PrivateKey privateKey = pair.getPrivateKey();
		PublicKey publicKey = pair.getPublicKey();
		SecureMessage encryptor = new SecureMessage(privateKey, publicKey);
	String test="Hello World";
		byte[] encryptedMessage = encryptor.wrap(test.getBytes());
		System.out.println(encryptedMessage);

Use this code to run.

But Facing error
Exception in thread "main" java.lang.UnsatisfiedLinkError: no themis_jni in java.library.path

I tried by import  libthemis_jni.so as jar but it also giving error.

Now I am stuck here.

Can you share steps what should I do after this?

**Comment by karenswry** [comment]
Try looking more closely into the [following](https://github.com/cossacklabs/themis/wiki/Java-and-Android-Howto#installing-themis-and-themis-jni-wrapper) piece of the Themis documentation and see the [examples](https://github.com/cossacklabs/themis/blob/master/src/wrappers/themis/java/com/cossacklabs/themis/SecureCell.java). Also - [this is](https://github.com/cossacklabs/themis/blob/master/.circleci/config.yml) how we compile Themis using Circle CI.
We are trying to figure out what could be going wrong in your case and the more details you provide, the easier it will be to help you.
Thank you.
Karen

**Comment by sourabhlodha** [comment]
@karenswry 
Can you explain this line
System.loadLibrary("themis_jni");

I changed to 
	System.loadLibrary("libthemis_jni.so");

Now it will show me the error.
Can you tell me what will be exactly themis_jni is the .so file or some folder.

**Comment by vixentael** [comment]
@sourabhlodha 

According to error message you got, I think one step you're missing is to provide a library path for compiled Themis library in your project.

1. After running `make themis_jni` you should see `libthemis_jni.so` in `/build` folder. This is complied Themis library for Java.
2. Copy `libthemis_jni.so` to your project into `/lib` folder (I prefer lib folder, but it depends on how do you usually link compiled libraries).
3. Specify path to libthemis_jni library in your project either using `-Djava.library.path=<path-to-your-project-folder>/lib` or using your IDE (https://www.chilkatsoft.com/java-loadlibrary-windows.asp, https://stackoverflow.com/questions/19308010/how-to-set-the-java-library-path-in-intellij-idea).
4. Copy all `.java` files from `src/wrappers/themis/java/com/cossacklabs/themis` to your project.
5. `import com.cossacklabs.themis.*;` in your code.
6.  Use your code

```
Keypair pair = KeypairGenerator.generateKeypair();
PrivateKey privateKey = pair.getPrivateKey();
PublicKey publicKey = pair.getPublicKey();
SecureMessage encryptor = new SecureMessage(privateKey, publicKey);
String test="Hello World";
byte[] encryptedMessage = encryptor.wrap(test.getBytes());
System.out.println(encryptedMessage);
```

Tell me if it helped

**Comment by sourabhlodha** [comment]
@karenswry 
I am getting this error
/usr/lib/jvm/java-8-openjdk-amd64/bin/java: symbol lookup error: /home/sourabh/libthemis_jni.so: undefined symbol: EVP_PKEY_new

**Comment by vixentael** [comment]
Which step is causing this error?

**Comment by sourabhlodha** [comment]
@vixentael 
The error occur in mention below line.
byte[] encryptedMessage = encryptor.wrap(test.getBytes());

**Comment by vixentael** [comment]
Okay, so basically you were able to compile `libthemis_jni.so`, put it to the correct folder, run the app, and now you see error.

`EVP_PKEY_new` is method from OpenSSL library.

The error log `bin/java: symbol lookup error` means that java can't find and link OpenSSL library while running your project.

Please specify what OpenSSL version do you use and where is it located. [This issue might be helpful](https://github.com/xhs/librtcdc/issues/19#issuecomment-249949087).


Meanwhile, we have updated example projects for Java and Android.

https://github.com/cossacklabs/themis-java-examples

Examples were built on MacOS, so `libthemis_jni` is compiled as suffix `dylib` library, however they illustrate how to link library to the project and how to use it. 

You can download `java-example`, change `libthemis_jni.dylib`  to your `libthemis_jni.so` and try to compile the project.

**Comment by sourabhlodha** [comment]
@vixentael 
I tried to configure openssl but still facing same issue
/usr/lib/jvm/java-8-openjdk-amd64/bin/java: symbol lookup error: /home/sourabh/libthemis_jni.so: undefined symbol: EVP_PKEY_new

**Comment by sourabhlodha** [comment]
@vixentael 
I also tried the given example mention above in your last solution.But it also give me the error
/usr/lib/jvm/java-8-openjdk-amd64/bin/java: symbol lookup error: /home/sourabh/libthemis_jni.so: undefined symbol: EVP_sha256

**Comment by karenswry** [comment]
@sourabhlodha 
It looks like you’re having problems with OpenSSL in your system.
Try running this example - it will help clarify if your OpenSSL and Java environment are configured correctly. Please note that in the example the fragment that deals with encryption is commented out and by default, the example performs decryption. You need to uncomment it first and try encrypting something:
https://www.javatips.net/api/haox-master/3rdparty/not-yet-commons-ssl/src/main/java/org/apache/commons/ssl/OpenSSL.java

**Comment by sourabhlodha** [comment]
@karenswry 
I tried this but still not able to resolve the issue.
If possible can you share me any example for windows10 64bit.

**Comment by vixentael** [comment]
Hi @sourabhlodha 

We prepared a step-by-step instruction how to install and compile Themis and run example project on Ubuntu Xenial. 

Most steps are described in [Java and Android Howto](https://github.com/cossacklabs/themis/wiki/Java-and-Android-Howto), however we provide you a necessary explanations for each of them: 

**1. We installed clean Ubuntu Xenial with java:**

```
shad@cl:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

shad@cl:~$ dpkg -l | grep jdk
ii  default-jdk                    2:1.8-56ubuntu2             amd64  Standard Java or Java compatible Development Kit
ii  default-jdk-headless           2:1.8-56ubuntu2             amd64  Standard Java or Java compatible Development Kit (headless)
ii  openjdk-8-jdk:amd64            8u171-b11-0ubuntu0.16.04.1  amd64  OpenJDK Development Kit (JDK)
ii  openjdk-8-jdk-headless:amd64   8u171-b11-0ubuntu0.16.04.1  amd64  OpenJDK Development Kit (JDK) (headless)
ii  openjdk-8-jre:amd64            8u171-b11-0ubuntu0.16.04.1  amd64  OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64   8u171-b11-0ubuntu0.16.04.1  amd64  OpenJDK Java runtime, using Hotspot JIT
``` 

**2. Download and install JetBrains IDEA as Java IDE**

```
### Download, install and Run Idea
cd ~
# download ideaIC.tar.gz
tar xfz ideaIC*
sudo mv ./idea-IC-* /opt/
cd /opt/idea-IC-*/bin/
./idea.sh
```

**3. Install all dependencies, download and install Themis**

```
### Install themis
sudo apt -y install git build-essential openssl libssl-dev default-jre default-jdk
cd ~
git clone https://github.com/cossacklabs/themis.git
cd themis/
make
make themis_jni
sudo make install
```

**4. Download [Themis java example project](https://github.com/cossacklabs/themis-java-examples) and change `libthemis_jni.dylib` to `libthemis_jni.so` compiled on previous step**

```
### Download and prepare project
cd ~
git clone https://github.com/cossacklabs/themis-java-examples.git
cp /usr/lib/libthemis_jni.so ~/themis-java-examples/java-example/lib/
rm ~/themis-java-examples/java-example/lib/libthemis_jni.dylib
```

**5. Run project in IDEA**
- open Idea
- open `~/themis-java-examples/java-example` folder
- set SDK
- build
- run

**6. See successfully compiled up and running Themis java example project:**

![screen_sharing_picture_august_3 _2018_at_13 36 30_gmt_3](https://user-images.githubusercontent.com/2877920/43641006-b68122ea-972a-11e8-91bf-3de59e71e2c9.png)

--------------

If performing these steps will lead to OpenSSL configuration errors on your system, most likely something is wrong with OpenSSL installation on your system.

**Comment by sourabhlodha** [comment]
Hi @vixentael 

Can you share the steps in windows also as It doesn't work in Ubuntu so Let me try with Windows10 64 bit OS.

**Comment by vixentael** [comment]
@sourabhlodha 

We provided a full step-by-step guide for compiling and using Themis on Ubuntu Xenial, as you previously asked. Which step is failing on your side?

----------

Themis doesn't have ready-to-use installation command for Windows, you should compile it from sources using GCC.

Basically, you have two options:

**Compiling directly on Windows**

1. Install [OpenSSL for Windows](https://wiki.openssl.org/index.php/Binaries).
2. Install [GCC for Windows](https://www3.ntu.edu.sg/home/ehchua/programming/cpp/gcc_make.html), for example [MinGW-w64](http://mingw-w64.org/doku.php).
3. Update [`makefile`](https://github.com/cossacklabs/themis/blob/master/Makefile) to be run for Windows: 
    - set `SHARED_EXT` to `dll` as library extension
    - update `CFLAGS`, `LDFLAGS` with correct paths for your system.
4. Run make.

**Compiling on Ubuntu for Windows x64**
_(preffered)_

1. Install GCC compiler for producing Windows executables, [this posts](http://www.blogcompiler.com/2010/07/11/compile-for-windows-on-linux/) suggests using [mingw-w64](https://stackoverflow.com/questions/38786014/how-to-compile-executable-for-windows-with-gcc-with-linux-subsystem/38788588), for example:

```sudo apt-get install mingw-w64```

2. Run `x86_64-w64-mingw32-gcc` as your gcc compiler.
3. Update [`makefile`](https://github.com/cossacklabs/themis/blob/master/Makefile) to generate dll: 
    - set `SHARED_EXT` to `dll` as library extension
4. Run make.

-----------

If you succeed in compiling `themis.dll` library for Windows, consider opening a PR with `makefile` changes, we would be grateful to merge it.

**Comment by vixentael** [comment]
@sourabhlodha, any updates?

**Comment by sourabhlodha** [comment]
@vixentael  Not able to run in my project.

**Comment by vixentael** [comment]
Sorry to hear that.

Themis `makefile` is targeted to run on Unix/Linux environments, but we do manual building and testing on Windows OS using steps as I described above.

Would you mind sharing particular steps that are failing for you either for Windows or for Ubuntu, so we can help you?

**Comment by vixentael** [comment]
Dear @sourabhlodha, it's a pity that both ways to solve a problem didn't work for you. 

We will consider this issue closed, but we're happy to answer any questions about [our products and libraries](https://www.cossacklabs.com/) if you have them.
