### ISSUE TITLE
Secure Comparator example

### ISSUE THREAD

**Issue by julepka** [cossacklabs/themis#341]
Can you please create a sample project to demonstrate Secure Comparator usage? While I'm a mobile developer I'm having hard times to implement server part. Your sample project https://github.com/cossacklabs/theswiftalpsdemo is very useful and it would be nice to see a similar one for Secure Comparator. Or at least simple instructions how to modify it to add Secure Comparator functionality. Thanks!

**Comment by vixentael** [comment]
Sure, will try to add some example.

Do you prefer HTTP of websockets as transport layer?

**Comment by julepka** [comment]
HTTP sound good. Thanks a lot!

**Comment by vixentael** [comment]
Sorry, this issue is just too old. We still didn't have python<>iOS secure comparator example, but maybe we won't make it in nearest future.
