### ISSUE TITLE
Themis 0.10.2 doesn't compile on iOS device due to bitcode

### ISSUE THREAD

**Issue by popaaaandrei** [cossacklabs/themis#406]
### Issue description
We have 2 iOS projects that were using 0.10.0 successfully.
After updating to themis 0.10.2 they don't compile anymore (with devices attached), the linker reports that themis is not build using bitcode (although the flag is there). My hypothesis is that it's related to the -DLIBRESSL flag. After deleting all those flags sometimes it works. Reverting back to 0.10.0 did the trick.

### Environment info

**OS:** iOS

**Themis version:** 0.10.2

**Installation way:**
 - pod update (updated from 0.10.0 to 0.10.2)

**Crypto provider:** OpenSSL / BoringSSL / LibreSSL (v0.0.0)
Just normal pod install, whatever SSL flavour it installs.

**Comment by vixentael** [comment]
Thank you Andrei :)

It's kinda weird, we put some efforts to enable bitcode in latest minor release, but maybe I haven't taken into account all cases.

I'm currently testing another way to tell CocoaPods that bitcode is enabled, will let you know when succeed.

This podspec has passed all tests however, but I'll take a fresh look tomorrow.
https://gist.githubusercontent.com/vixentael/68e0fdc46af0bd2a806836167d9c1b59/raw/110a52344e95d04ddb102429da5b22ba73875029/themis.podspec

**Comment by vixentael** [comment]
Fixed in https://github.com/cossacklabs/themis/pull/407, new podspec uploaded, feel free to use `0.10.3`
