### ISSUE TITLE
soter_rand(): cast size_t -> int -> size_t unnecessary and potentially lossy

### ISSUE THREAD

**Issue by veorq** [cossacklabs/themis#477]
In https://github.com/cossacklabs/themis/blob/master/src/soter/boringssl/soter_rand.c#L21, `soter_rand()` takes a `size_t` and casts it to `int` to pass it to `RAND_bytes(*, size_t)`; unlike OpenSSL, boringSSL's  `RAND_bytes()` takes a `size_t` length and not an `int`. If more than ~4GB are requested then the call will therefore fail to return the right amount.

Likewise, the OpenSSL counterpart may check for overflows in the (needed) cast https://github.com/cossacklabs/themis/blob/master/src/soter/openssl/soter_rand.c.

**Comment by vixentael** [comment]
thank you, makes sense :)
will fix.
