### ISSUE TITLE
Presence of 32bit native libraries without 64bit support

### ISSUE THREAD

**Issue by vanceanderson41** [cossacklabs/themis#479]
I have:

- [X] searched open and closed issues for duplicates

----------------------------------------

### Issue description

According to this initiative from Google that will soon enforce 64bit support: https://developer.android.com/distribute/best-practices/develop/64-bit, should users of this repository expect to get an update that complies with the directive by supplying a 64-bit . variant of `libthemis_jni.so`?

### Environment info

**OS:** Android (min: 21, target: 28)

**Themis version:** 0.11.0 (`com.cossacklabs.com:themis:0.11.0`)

**Installation way:**
 - [ ] downloaded tag from github
 - [X] via package manager
 - [ ] built from source

**Crypto provider:** **I don't know** / OpenSSL / BoringSSL / LibreSSL

**Comment by vixentael** [comment]
Well, Themis should support 64 bits architectures easily, because it's most commonly used on other platforms. But I'll triple check that we build Themis with correct flags for Android and that 64-bit archi slices are included.

I'll keep updating this thread.

**Comment by vanceanderson41** [comment]
Any update here @vixentael ?

Receiving notifications from the store that we won't be able to publish updates to our app while this isn't satisfied

**Comment by vixentael** [comment]
Yep, I have verified that we do supply following architectures:

```
x86_64
x86
arm64-v8a
armeabi-v7a
```

You can double checked Themis architectures that are packed into your compiled application using Android Studio "Build > Analyze APK" command:

<img width="440" alt="Screen Shot 2019-07-10 at 3 32 14 PM" src="https://user-images.githubusercontent.com/2877920/60969320-ec98ce00-a327-11e9-8f8e-e2843ca77fb1.png">

**Comment by vixentael** [comment]
@vanceanderson41 could you double check if you see x64 libraries in your app? otherwise i'm closing the issue

**Comment by vanceanderson41** [comment]
@vixentael I will double check and respond in this thread. Thanks!

**Comment by vanceanderson41** [comment]
Confirmed. Thanks for the support @v
