### ISSUE TITLE
Cannot install Themis via Cocoapods

### ISSUE THREAD

**Issue by drewpitchford** [cossacklabs/themis#481]
I have:

- [x ] searched open and closed issues for duplicates

----------------------------------------

### Issue description

When I try to install Themis into a new project, pod install fails. Additionally, it seems pod update doesn't download the spec(s).

### Environment info

installation

**OS:** OS name and version
MacOS Mojave

**Themis version:** 0.x.y
Latest

**Installation way:**
 - [ ] downloaded tag from github
 - [x ] via package manager
 - [ ] built from source

**Crypto provider:** I don't know / OpenSSL / BoringSSL / LibreSSL
OpenSSL

### Link to example project
[JWE-Themis.zip](https://github.com/cossacklabs/themis/files/3297683/JWE-Themis.zip)

**Comment by vixentael** [comment]
please change source in your Podfile to `source 'https://github.com/CocoaPods/Specs.git'`

**Comment by drewpitchford** [comment]
@vixentael Thanks! I had the source set correctly, but I had to add `project 'MyProject.xcodeproj'` to the podfile, which I've never done before. Anyways, it works now!

**Comment by vixentael** [comment]
sounds great!
