### ISSUE TITLE
possible memory leak in soter_rsa_priv_key_to_engine_specific() [OpenSSL]

### ISSUE THREAD

**Issue by outspace** [cossacklabs/themis#514]
In [https://github.com/cossacklabs/themis/blob/master/src/soter/openssl/soter_rsa_key.c](https://github.com/cossacklabs/themis/blob/master/src/soter/openssl/soter_rsa_key.c) In function soter_rsa_priv_key_to_engine_specific() when you checking for BIGNUM allocation you don't free previous allocated BIGNUM.
```
if (!rsa_dmp1) {
        RSA_free(rsa);
        return SOTER_NO_MEMORY;
}
```
In this case rsa_q, rsa_p, rsa_d, rsa_e  will leak.

**Comment by outspace** [comment]
Maybe it will be a good idea to use BN_secure_new() for allocation

**Comment by vixentael** [comment]
Thank you, we'll take a deeper look!

Also, we'll look at similar piece for BoringSSL
https://github.com/cossacklabs/themis/blob/master/src/soter/boringssl/soter_rsa_key.c#L394

Have you found it by manual scanning, or using some tool?

**Comment by outspace** [comment]
It just static code analysis. In your thread of BoringSSL you are using rsa structure directly and if something go wrong it will be free in RSA_free().

**Comment by Lagovas** [comment]
oh yes, looks like we need here a lot of bn_free... 
and manually re-check with valgrind and check that he really not found these leaks

@outspace which static code analysis you used? if it is not a secret )

**Comment by ilammy** [comment]
@outspace, thank you for your keen eyes. Known leaks have been eliminated.
