### ISSUE TITLE
possible memory leak in soter_rsa_pub_key_to_engine_specific() [OpenSSL]

### ISSUE THREAD

**Issue by outspace** [cossacklabs/themis#515]
In [https://github.com/cossacklabs/themis/blob/master/src/soter/openssl/soter_rsa_key.c](https://github.com/cossacklabs/themis/blob/master/src/soter/openssl/soter_rsa_key.c), in function 
soter_rsa_pub_key_to_engine_specific() 
```
if (!rsa_n) {
        return SOTER_NO_MEMORY;
 }
``` 
don't free previously allocated rsa

**Comment by Lagovas** [comment]
agree, we should add `RSA_free(rsa)`

**Comment by ilammy** [comment]
Known leaks have been eliminated.
