### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by lordcodes** [cossacklabs/themis#530]
I have:

- [X] searched open and closed issues for duplicates

----------------------------------------

### Issue description

When using Xcode 11 many developers will inevitably be moving dependencies over to the Swift Package Manager instead of using Cocoapods or Carthage.

**Comment by vixentael** [comment]
SPM support is definitely on our list, but we'd be happy to get some help here :)

**Comment by vixentael** [comment]
As Apple Silicon is here, and it makes impossible to have `.framework` that contains arm64 slice and arm64-iphonesimulator slice, we're looking at building Themis as `.xcframework` now.

**Comment by heysaik** [comment]
Any updates to this?

**Comment by vixentael** [comment]
work in progress, a bit stuck with xcframework'ing openssl

**Comment by vixentael** [comment]
I don't lie — we are working on SPM! :)
@julepka

[Xcode is tricky to work with large C-based projects, so for starters we will distribute ThemisSPM as built XCFramework, not as code.]

https://github.com/cossacklabs/themis/pull/789#pullrequestreview-610841800
https://github.com/cossacklabs/openssl-apple/pull/22

ETA: couple of weeks for beta release, ~1-2 month for stable release with docs and examples.

**Comment by vixentael** [comment]
It's official!

Since [0.13.8](https://github.com/cossacklabs/themis/releases/tag/0.13.8) Themis supports SPM!

Checkout docs:
https://docs.cossacklabs.com/themis/languages/swift/installation/#installing-with-spm

Viva @julepka 👏

**Comment by heysaik** [comment]
Awesome thank you!
