### ISSUE TITLE
memory usage in soter_asym_ka_init() [BoringSSL]

### ISSUE THREAD

**Issue by outspace** [cossacklabs/themis#533]
I'm not sure that it's correct to call **EVP_PKEY_CTX_free** in this function. Please look at it carefully.

**Comment by Lagovas** [comment]
I don't see why we should not to call `EVP_PKEY_CTX_free` on errors to free allocated memory but see that we should add call `EVP_PKEY_free(pkey);` with same reason as in #532 issue

**Comment by outspace** [comment]
It's not so simple, the reason not same. If we call free in this function than we will call free agan in **soter_asym_ka_cleanup**. That is why it should be nulled after free.

**Comment by Lagovas** [comment]
you are right that we should add nullifying pointers, but it does not make call `EVP_PKEY_CTX_free` incorrect here) 
and thanks, found the place where it may do some problems with second free call)
I think you are about https://github.com/cossacklabs/themis/blob/stable/src/themis/secure_session.c#L114 this place where in bad case it go here - https://github.com/cossacklabs/themis/blob/stable/src/themis/secure_session.c#L132
and call second time `EVP_PKEY_CTX_free`

so we should add `EVP_PKEY_free(pkey);` calls and nullify all freed pointers

**Comment by outspace** [comment]
> I think you are about https://github.com/cossacklabs/themis/blob/stable/src/themis/secure_session.c#L114 this place where in bad case it go here - https://github.com/cossacklabs/themis/blob/stable/src/themis/secure_session.c#L132
> and call second time EVP_PKEY_CTX_free

Yes, i mean this places. I agree with call of **EVP_PKEY_free(pkey)**, but it's not so critical as double-free of memory.

**Comment by ilammy** [comment]
Resource deallocation has been improved, fixing possible double-free issues.
