### ISSUE TITLE
memory usage in soter_asym_cipher_init()

### ISSUE THREAD

**Issue by outspace** [cossacklabs/themis#534]
I'm look at soter_asym_cipher_init() in BoringSSL and OpenSSL threads. In bad case of macro we call **EVP_PKEY_CTX_free** than we call **EVP_PKEY_CTX_free** again in **soter_asym_cipher_cleanup** that's why it shoud be nulled in BoringSSL too.

**Comment by Lagovas** [comment]
agree, we should nullify freed pointers to avoid problems with second `free` call

**Comment by ilammy** [comment]
Resource deallocation has been improved. Stored pointers in key generations routines are now zeroed out after freeing them.
