### ISSUE TITLE
Can't archive Xcode project with themis installed

### ISSUE THREAD

**Issue by chrisleversuch** [cossacklabs/themis#538]
I have:

- [X] searched open and closed issues for duplicates

----------------------------------------

### Issue description

When archiving a project in Xcode that has themis installed, I get lots of Undefined symbol errors. It works fine running in the simulator and on a device.

[error.txt](https://github.com/cossacklabs/themis/files/3654795/error.txt)

I've tried creating a clean project, added themis as the only pod and get the same error when archiving. I've tried adding source and project lines to the Podfile but it didn't make a difference.

### Environment info

**OS:** macOS 10.14.6. Xcode 10.3

**Themis version:** 0.11.0

**Installation way:**
 - [ ] downloaded tag from github
 - [X] via package manager CocoaPods
 - [ ] built from source

**Crypto provider:** I don't know

### Link to example project

[Test2.zip](https://github.com/cossacklabs/themis/files/3654788/Test2.zip)

**Comment by vixentael** [comment]
thank you, @chrisleversuch! i'm taking a look now.

**Comment by vixentael** [comment]
oh, that's a dependency problem with latest [GRKOpenSSLFramework release](https://github.com/levigroker/GRKOpenSSLFramework/releases)

As a workaround, please use

```

pod 'themis', :podspec => 'https://gist.githubusercontent.com/vixentael/f21273963d09a7ec908e3a323e14a223/raw/bc51c8d7d37b7e034a687c4549e180d0398c1449/themis.podspec'
```

Meantime, I'll try to push this podspec that links to the pre-latest version GRKOpenSSLFramework. After push, you'll be able to use `pod themis, 0.12.3`, just give me ~1 hour.

Please try the workaround, meanwhile I'll push the update.

**Comment by chrisleversuch** [comment]
The workaround works for me, thanks

**Comment by vixentael** [comment]
@chrisleversuch you can use `pod 'themis', '0.12.2'` now.

Don't forget to run `pod install --repo-update` to make sure that Cocoapods repo knows about latest release.

**Comment by chrisleversuch** [comment]
Great, thanks
