### ISSUE TITLE
Compiling Themis iOS lib causes billions of warnings

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#55]
Themis and Soter core (not iOS wrapper!) are causing many warnings when are compiled by Xcode.

<img width="273" alt="screen shot 2015-09-30 at 03 06 59" src="https://cloud.githubusercontent.com/assets/2877920/10181426/9d2cfe0a-6720-11e5-8811-c10d4c569cd9.png">

You can build [this project](https://github.com/cossacklabs/mobile-websocket-example/tree/master/ios/WebsocketExampleClient) using Xcode7 with default settings, pointing on x64 device or simulator to see warnings.

In iOS world having even one warning with default Xcode warning flags is a bad practice.

@mnaza please, take a look

**Comment by cossacklabs** [comment]
@mnaza said he fixed most of them, Andrey, why don't you write us a small report? :)

**Comment by vixentael** [comment]
thank you, @mnaza for fixing lots of warnings!

Now i see only 3 of them (all from `soter_ec_keys.c` file)
<img width="256" alt="screen shot 2015-10-03 at 15 38 04" src="https://cloud.githubusercontent.com/assets/2877920/10262928/09f0defa-69e5-11e5-85dd-f632f4e02bab.png">

Great job!

**Comment by mnaza** [comment]
Two other warning are the cause of hatred XCode to "goto"

**Comment by gene-eu** [comment]
So, can we close this one now, @vixentael? Or remaining warnings are still important ones?

**Comment by vixentael** [comment]
well.. new code - new warnings ;)

Current situation (build Themis example with latest pod using xcode 7.1 with default warning levels)

**45 warnings**

most of them - precision on x64
<img width="710" alt="screen shot 2015-11-02 at 02 50 09" src="https://cloud.githubusercontent.com/assets/2877920/10872630/26ab77e4-810f-11e5-825e-4eaf2be0c3ee.png">

these two are `goto` issues, right?
<img width="692" alt="screen shot 2015-11-02 at 02 50 00" src="https://cloud.githubusercontent.com/assets/2877920/10872631/29306cea-810f-11e5-91c8-32053ec1438a.png">

Usually we're disabling warnings from Pods adding line `inhibit_all_warnings!` to the Podfile. I've disabled warnings for our test projects too.

Anyway I really think that if we can decrease number of warnings, we should try.

**Comment by vixentael** [comment]
thanks @mnaza! most warnings disappear, so i'll close the issues
