### ISSUE TITLE
Swift support for Themis-iOS

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#58]
It's time to write some swift code!

**Comment by vixentael** [comment]
well, on the current moment, we will use objc wrapper with bridging header

**Comment by vixentael** [comment]
@mnaza @gene-eu take a look.. i dig into updating wiki examples for now

**Comment by gene-eu** [comment]
I overheard there's no Secure Session yet?

**Comment by vixentael** [comment]
Right, we should rewrite [websockets example](https://github.com/cossacklabs/mobile-websocket-example) in Swift too

**Comment by vixentael** [comment]
Btw, please check new Swift wiki page https://github.com/cossacklabs/themis/wiki/Swift-Howto

**Comment by vixentael** [comment]
working on secure session sample #109

btw, i'm going to rewrite [themis-server example](https://github.com/cossacklabs/themis/tree/master/docs/examples/Themis-server ) instead of websockets

**Comment by vixentael** [comment]
Rewrote Themis Server example (including SSession), #110 

For better support I believe that we need to update ObjC wrapper code with [nullability and optionals](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-ID53).

**Comment by vixentael** [comment]
[Swift wiki page](https://github.com/cossacklabs/themis/wiki/Swift-Howto) is updated with SecureSession example

**Comment by vixentael** [comment]
@gene-eu @mnaza any thoughts?

**Comment by gene-eu** [comment]
Seems legit. If any iOS person will object - just reopen this.
