### ISSUE TITLE
Docs updates

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#59]
1. make uninstall

In testing this I noticed that uninstall can fail because of it's dependencies:
uninstall: phpthemis_uninstall rubythemis_uninstall pythonthemis_uninstall

If you have not installed phpthemis then no makefile will have been generated in src/wrappers/themis/php so the attempt to uninstall phpthemis with make distclean fails and causes the whole uninstall process to stop. I don't know if this would also apply similarly for python or ruby.

2. One possible "Troubleshooting" case is the need to:
sudo make install

3. A more esoteric "Troubleshooting" case is OS X 10.11 SIP (aka Rootless). The makefile itself now does all the right things and all you need to do is:
make phpthemis_install PREFIX=/usr/local

However, the phpize generated ./configure uses ```php-config --extension-dir''' to determine the final destination for phpthemis.so. The default /usr/bin/php-config will return something like /usr/lib/php/extensions/no-debug-non-zts-20121212 ... which is non-writable with SIP.

A solution to this (there may be others) is to:
1. Create a directory such as /usr/local/lib/php/extensions/sipfix
2. Copy /usr/bin/php-config to /usr/local/bin/php-config and amend it to reference the new directory
3. make phpinstall PREFIX=/usr/localwill now install /usr/local/lib/php/extensions/sipfix/phpthemis.so
4. In php.ini set extension= /usr/local/lib/php/extensions/sipfix/phpthemis.so (i.e. use the full path)

**Comment by mnaza** [comment]
I correct makefile uninstall target. Now before "make distclean" it will check is phpthemis makefile exitst

**Comment by gene-eu** [comment]
What about the same checks for other languages?

**Comment by mnaza** [comment]
others have already cheked

**Comment by vixentael** [comment]
guys, any more thoughts on this?

**Comment by gene-eu** [comment]
@mnaza ?

**Comment by vixentael** [comment]
hate having open issues too long :) 
guys, can we close it? @gene-eu @mnaza
