### ISSUE TITLE
Make exceptions and errors consistent on all platforms

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#63]
**Aim**: make user experience in reading exceptions and errors useful, not frustrating
**How to**: take 'themis_secure_cell_decrypt_seal error' and transform it to 'Secure Cell failed decrypting, seal is invalid", for example

**Comment by vixentael** [comment]
Also, rename `error.h` files in different folders (same names cause clang `duplicate files` warning). Better to name files with prefix. so_error.h (soter), th_error.h (themis) etc

**Comment by mnaza** [comment]
Renaming headers it is not good idea. This errors appear by xcode features, not by obj-c. If in xcode project pass "USE_HEADERMAP" to "NO" this errors will disappeared.

**Comment by vixentael** [comment]
Current podspec contains `'USE_HEADERMAP' => 'NO'`, errors are still there.

**Comment by gene-eu** [comment]
Well, these issues don't seem to be inter-related (renaming error files and making exceptions verbose are different problems), but let's keep 'em linked.
