### ISSUE TITLE
Release to Ubuntu 20.04

### ISSUE THREAD

**Issue by anuppari** [cossacklabs/themis#661]
**Is your feature request related to a problem? Please describe.**
Currently, there is no pre-built packages for themis available in the Ubuntu 20.04 LTS package repository.

**Describe the solution you'd like to see**
Since Ubuntu 20.04 is the latest LTS release, it would be helpful to release packages for Ubuntu 20.04

**Describe alternatives you've considered**
Require users on 20.04 to build from source

**Comment by ilammy** [comment]
@anuppari, good news: soon-to-be-released Themis 0.13 will include packages for Ubuntu 20.04 Focal Fossa 💪 It's like a week or two away.

**Comment by vixentael** [comment]
0.13.0 Themis is released, and it supports Ubuntu 20.04:
https://docs.cossacklabs.com/themis/installation/installation-from-packages/
