### ISSUE TITLE
Update the docs about cryptographic choices

### ISSUE THREAD

**Issue by cossacklabs** [cossacklabs/themis#7]
... to more correctly reflect current crypto algorithms in charge for all current crypto primitives. It could be simply done by interpreting corresponding defines, e.g. 

    #define THEMIS_SYM_KEY_LENGTH SOTER_SYM_256_KEY_LENGTH
    #define THEMIS_AUTH_SYM_ALG (SOTER_SYM_AES_GCM|THEMIS_SYM_KEY_LENGTH)

in `sym_enc_message.c`.

**Comment by cossacklabs** [comment]
This seems to be inline with what you're doing, Andrey.

**Comment by gene-eu** [comment]
This is what issue #8 is all about, no need to separate.
