### ISSUE TITLE
Add Apple Silicon/ARM64 macOS support; Xcode 12 / Xcode 12.2

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#725]
Well, as Apple Silicon comes, we should add `arm64` slice into Themis iOS, Themis macOS, and OpenSSL [T1822].

Currently, we use workaround to disable arm64-iphone-simulator for iOS builds and to enable `buildActiveArchitectureOnly=YES` for macOS builds. This allows to build apps and submit them to iOS / macOS App Store without arm64 slice.

Obviously, this is a temporary solution, a workaround, to allow developers continue using Themis for their apps and update to Xcode 12.

We're working on adding arm64 slice to OpenSSL (tricky) and Themis (easy).

See related changes: #713 #719.

Guides:

- [Apple, building universal macos binary](https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary)
- OpenSSL ARM64 by @adib https://github.com/balthisar/openssl-xcframeworks/pull/6
- https://github.com/openssl/openssl/issues/12254
- https://github.com/keeshux/openssl-apple/issues/21

Corresponded reading:

- [Xcode 12 beta 4 - error compiling for Simulator, set active architecture only true](https://developer.apple.com/forums/thread/656509?page=3)
- [remove valid archs](https://github.com/CocoaPods/CocoaPods/issues/10059)
- https://github.com/realm/realm-cocoa/issues/6619
- https://github.com/Carthage/Carthage/issues/3019

**Comment by thefaj** [comment]
A minor but important note: it's spelled "Apple Silicon" not "Apple Silicone".

**Comment by vixentael** [comment]
thank you @thefaj! I'm doing this mistake again and again 😅 embarrassing.

**Comment by vixentael** [comment]
Latest Themis 0.13.4 support ARM64 for macOS. See #736 #740 #739 #738.
