### ISSUE TITLE
Build error objc project with Themis 0.9.1 and xcode 7.1

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#73]
ThemisTest (objc main example) stops building on Xcode 7.1 due to imperfection of our PodSpec. 

[0.9.1 podspec](https://github.com/CocoaPods/Specs/blob/3594ff2908bea9f0d59bfd30baa28b67ada025f3/Specs/themis/0.9.1/themis.podspec.json) has several `error.h` files at the same subfolder and it confuses xcode and leads to build error.
<img width="465" alt="screen shot 2015-11-02 at 02 22 32" src="https://cloud.githubusercontent.com/assets/2877920/10872652/a7d12b66-810f-11e5-86ec-db2b5dbfaa43.png">

Build errors:
<img width="748" alt="screen shot 2015-11-02 at 02 13 08" src="https://cloud.githubusercontent.com/assets/2877920/10872684/0040cd56-8110-11e5-8855-b5f48215a229.png">

[Latest podspec](https://github.com/cossacklabs/themis/blob/master/themis.podspec) is based on subspecs and doesn't cause build error. 

Users that install Themis directly like `pod 'themis', :git => "https://github.com/cossacklabs/themis.git"` are not affected. 

Anyway, we really need to update podspec ASAP. We can simply bump version to 0.9.1.1 or to release 0.9.2. 

@gene-eu what do you think?

**Comment by gene-eu** [comment]
According to my checklist, chances are high we will release 0.9.2 this week, so, maybe this should push us to finish minor fixes faster?

**Comment by vixentael** [comment]
tag pushed, podspec updated and pushed to cocoapods repo

https://github.com/cossacklabs/themis/commit/b2a5f4ccf6806d523a373b1e416240988c8d6cd8
https://github.com/cossacklabs/themis/commit/af69e30abde59363714704b894fe25b40fc429b8

https://github.com/cossacklabs/themis/releases/tag/0.9.2
