### ISSUE TITLE
[Question] Compatibility with react-native — DONE ✅

### ISSUE THREAD

**Issue by rytyr** [cossacklabs/themis#737]
I have googled around, read through on issues and could not find any related info nor guides for using themis on React-Native.

Does themis supported in react-native?

Thanks

**Comment by ilammy** [comment]
Hi @rytyr, thanks for your interest in Themis!

We have not been testing Themis with React Native specifically, but I strongly expect [**WasmThemis**](https://docs.cossacklabs.com/themis/languages/wasm/) to be compatible with React Native. It's available as [`wasm-themis`](https://www.npmjs.com/package/wasm-themis) in the npm.js repositories. Here's the [API guide](https://docs.cossacklabs.com/themis/languages/wasm/features/) too. You can try it out.

We will check React Native compatibility too and will post our results in this issue as well.

**Comment by tschanz-pcv** [comment]
Would be great to get Themis for React Native. If possible using the native iOS/Android/(Windows) libraries as a RN Native Module and not just the JS version.

I'm not sure that wasm will work. From all that I could gather, wasm is sadly not supported on RN. Alternatively it could be compiled to asm.js?

I guess the NodeJS version uses many NodeJS platform APIs? If not maybe the documentation could be extended with what needs to be polyfilled.

**Comment by maxammann** [comment]
We are currently writing a period tracker using themis. We use the Android bindings currently and use NativeModules: https://github.com/cyla-app/cyla-app

The downside is ofc that you have to implement some logic in android and ios. iOS is still missing.

**Comment by snehapatil90** [comment]
Hi everyone,

Can anyone confirm what is the compatible library for this in react native ?

**Comment by maxammann** [comment]
> Hi everyone,
> 
> Can anyone confirm what is the compatible library for this in react native ?

Sadly it is not really compatible. You have to use the android and ios bindings. The wasm bindings wont work. We wrote some bindings manually in  https://github.com/cyla-app/cyla-app

It is not yet compatible with iOS.

**Comment by vixentael** [comment]
Currently, Themis doesn't ship ready-to-use React Native wrapper. But as @maxammann mentioned, they wrote bindings and use Themis successfully. 

@maxammann correct me if I'm wrong, this is the bindings file, right?
https://github.com/cyla-app/cyla-app/blob/main/frontend/android/app/src/main/java/app/cyla/util/Themis.kt

**Comment by maxammann** [comment]
Not really, there we are just implementing some code which uses themis for android.
We did not expose the whole themis library there, but decided to implement some "business logic" which requires android in Kotlin and just send data between RN and the native side.

So this is not really reusable, but shows how it could be done.

**Comment by vixentael** [comment]
So yeah, you build bindings between Themis Android and RN side for Secure Cell

**Comment by gaodeng** [comment]
@vixentael  any news?

**Comment by vixentael** [comment]
Hi! Themis React Native package is now in beta. It's working, and is fully compatible with other Themis wrappers (native iOS, native Android, python, Go, etc). We tested Themis RN with different iOS and Android apps, and can confirm it will be awesome :)

We are on the latest stage before public release.

Here is the temporary home of Themis RN:
https://github.com/radetsky/react-native-themis

Our plans:

[ ] write product docs how to use Themis RN
[ ] merge Themis RN into the main Themis repository (here)
[ ] polish examples etc

But the basics are working :)
You can try https://www.npmjs.com/package/react-native-themis but please disregard the readme.

**Comment by vixentael** [comment]
Status update: Themis RN docs are available:
https://docs.cossacklabs.com/themis/languages/react-native/

Our plans:

[x] write product docs how to use Themis RN
_>—— we are here ——<_
[ ] merge Themis RN into the main Themis repository (here)
[ ] polish examples etc

**Comment by maxencehenneron** [comment]
Hi, I appreciate the work that has been done. But wouldn't it be much faster with the new TurboModules architecture? 

Basically, currently, the native side calls the Themis C library and then returns the information to the JS side via a bridge. It creates overhead and slows the operation.

Turbomodules skip the native and bridge part entirely and establish direct communication between C++ and JS.  It's also more cross-platform as you do not have to write java and obj-c code.

**Comment by vixentael** [comment]
Status update: 

Themis RN docs are available:
https://docs.cossacklabs.com/themis/languages/react-native/

npm package is here
https://www.npmjs.com/package/react-native-themis

tag is here
https://github.com/cossacklabs/themis/releases/tag/0.14.4

Our plans:

[x] write product docs how to use Themis RN
[x] merge Themis RN into the main Themis repository (here)
[x] polish examples etc
_>—— we are here ——<_

**Comment by vixentael** [comment]
@maxencehenneron hi Maxence! Yes, you are right regarding performance issues. No one likes all these back-n-forth through language runtimes. 

We are looking into TurboModules, but honestly, they feel "too raw" as this moment. Themis is a complicated construction and we'd like to avoid extra bugs that we cannot control. As for now, we see many issues like https://github.com/react-native-community/discussions-and-proposals/issues/40#issuecomment-1086031920 Also, we follow TurboModules development closely, but it's a bit unclear how API will be changing in the nearest versions.

Our current plan is to wait for 0.70 probably and then try to migrate to TurboModules. Depending on how it will work, we might do a separate package for Themis with Turbo modules until we are sure that it's stable. The last thing we want is to create a package that will require constant fixing and will frustrate users. Cryptography is already frustrating enough, hehe.

If you have any good examples of complex libraries that use TurboModules approach, could you please point us there?

cc @radetsky @ilammy
