### ISSUE TITLE
Issues with AppSpector 1.3.5 and Themis 0.13.4

### ISSUE THREAD

**Issue by archana211** [cossacklabs/themis#741]
I am using cocoapods 1.10.0 , AppSpectorSDKE2E- 1.3.5 along with themis -0.13.4 on app launch getting "Library not loaded" error for themis but app works fine if i use cocoapods 1.9.3 , AppSpectorSDKE2E- 1.3.5 along with themis -0.13.3.

Is there any update in latest version (0.13.4)?

1. On app launch
2. See the following error:
dyld: Library not loaded: @rpath/themis.framework/themis
Referenced from: ~/Frameworks/AppSpectorSDKE2E.framework/AppSpectorSDKE2E
Reason: image not found

**Environment (please complete the following information):**
- OS: iOS 14
- Hardware: simulator
- Themis version: 0.13.4
- Installation way:  pod AppSpectorSDKE2E

**Comment by ilammy** [comment]
Hi @archana211, thank you for a report!

This seems to be a genuine issue with recently released Themis 0.13.4.

For CocoaPods, Themis 0.13.4 switches for dynamic linkage to static linkage. Unfortunately, we have not forseen the effect that this change might have on transitive dependency chains (i.e., when applications depend on a libraries and frameworks that depend on Themis). The situation here is that AppSpector's SDK still depends on the *dynamic* version of Themis, which 0.13.4 does not provide.

The workaround currently is to pin the version of Themis to 0.13.3 (or earlier), like you have done:
```
pod 'themis', '0.13.3'
```

We have also contacted AppSpector maintainers and they are working on releasing an updated version of the SDK which supports Themis 0.13.4. Once that hotfix is out, it should be possible to use a newer SDK and remove the pinned version.

I am sorry for the trouble that this have brought to you and other people.

**Comment by vixentael** [comment]
@archana211 thank you a lot for letting us so early. We release `0.13.4` just yesterday, so having such quick feedback really helps a lot.

That's a pity that we didn't foresee this issue before, but better later than never.

**Comment by archana211** [comment]
Okay , will go for fix version for now.
Thanks for the quick response.

**Comment by vixentael** [comment]
@archana211 AppSpectorSDKE2E has released new version `1.3.6` with hard-linked Themis `0.13.3`.

As we fix Themis, we'll ask @deszip to update AppSpector again :)

**Comment by vixentael** [comment]
The issue was hotpatched a month ago thanks to amazing speed of @deszip from AppSpector team, who pinned working Themis version.

Since then, we've fixed this issue (#750) and released [0.13.6](https://github.com/cossacklabs/themis/releases/tag/0.13.6).

Latest AppSpector uses fixed Themis.
