### ISSUE TITLE
[TODO] Migrate AndroidThemis from Bintray

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#776]
[JFrog shuts down Bintray service](
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), where we host android Themis:
https://bintray.com/cossacklabs/maven/themis

They suggest migrating to Maven Central.

We should investigate what changes are required in [src/wrappers/themis/android/build.gradle](https://github.com/cossacklabs/themis/blob/master/src/wrappers/themis/android/build.gradle) and potentially other android/Java related files to fix distribution pipeline.

## List of useful links:

* Potentially helpful twitter-thread from Brian Sonatype:
https://twitter.com/Brian_Fox/status/1357414525377642496

* Maven Central Requirements
https://central.sonatype.org/pages/requirements.html

* @asm0dey has kindly shared their `build.gradle` that uploads their lib to Maven Central for inspiration purposes
https://github.com/asm0dey/staks/blob/main/build.gradle

* Manual on manually moving libs from JCenter to Maven Central
https://www.marcogomiero.com/posts/2021/move-libray-jcenter-to-maven/

**Comment by ilammy** [comment]
Android Themis has been republished to Maven Central manually. It should be available under the same name.

```gradle
repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.cossacklabs.com:themis:0.13.1'
}
```

Currently only the latest version 0.13.1 is available, as it is the first one containing all the required metadata to be allowed into the Maven Central repo.

Things still to be done:
- republish old versions 0.10.0 through 0.12.0 if possible
- automate publishing process for future versions
- update CI pipelines to test against Maven Central

**Comment by vixentael** [comment]
Thank you, @ilammy!

Themis is available here
https://search.maven.org/artifact/com.cossacklabs.com/themis/0.13.1/aar

Things still to be done (cont):
[ ] test and update examples
[ ] update installation docs

**Comment by vixentael** [comment]
looks like @ilammy has updated gradle, docs, examples and produced a repeatable release manual. I suggest to close this issue, as other things (automation and moving old Themis libs to MC) are more "enhancements" than blockers.
