### ISSUE TITLE
[Question] How to use ZKP for Authentification

### ISSUE THREAD

**Issue by maxammann** [cossacklabs/themis#778]
We are struggling right now a bit to use the Secure Comparator as a way of authenticating. We are storing a has of a secret key in the servers database and at the plain secret key at the client.

Then we initiate a ZKP like here: https://github.com/cossacklabs/themis/blob/master/docs/examples/go/secure_comparator_server.go#L17

The client hashes the secret key proves the knowledge to the server.

Isn't there a flaw with this authentication? If the database and the hashed secret is leaked, then anyone with that data can authenticate against the server.

If you use a classical authentication schema with hashed passwords then this would not be the case as you would need to send the password to the server. This can also be though of as authentication by knowing the pre-image of the hashed value in the database. How you can not authenticate even if you have the database leak because you do not know the pre-image.

How to improve on this situation?

**Comment by maxammann** [comment]
I've also read this post: https://medium.com/@cossacklabs/zero-knowledge-protocols-without-magic-30729017f825

I think there are two goals for authentication:
* Password Leakage (which is addressed in the blog post)
* Avoiding authentication after database leakage (not addressed in the blog post)

Is there a simple way to the 2. goal? I think there isn't one which does not involve Public-Private key auth, signatures etc.

**Comment by gene-eu** [comment]
Your question is out of scope of SComparator functionality. Simple primitives are typically very precise in their utility, this is the case. SC is designed to let 2 parties compare a secret without risking: 

* dishonest server collecting secret-related data from authentication conversation (which can be used to replay authentication or reconstruct the secret or its derivatives).
* passive/active man-in-the-middle observers collecting the secret or its hashes by observing the traffic. 

SC does not change anything in "classical authentication schema" (whatever that is) with regard to what you store. SC only replaces the method for parties to agree that they share something. SC has nothing to do with the way you store your secrets or what exactly you compare. Thus, it has very little impact on what gets leaked from your database. 

Whole design discussion around "avoid credential reuse after database breach" is:
* too vague to provide helpful response
* irrelevant in context of cryptographic library,
 
so I have to close this ticket. 

However, if you're looking for design advice around SC and are willing to provide enough precise use-case, threat/risk model and the failure event you're protecting against, don't hesitate to get in touch via dev@cossacklabs.com and someone from the team will try to answer once we have free time.

**Comment by maxammann** [comment]
Alright, no problem. I'll drop you an email when I have time to elaborate more on our project and attacker models :)
