### ISSUE TITLE
WASM Failure on Safari on macOS and iOS

### ISSUE THREAD

**Issue by CACUser** [cossacklabs/themis#798]
During decryption it fails with this message : Themis: SecureCellSeal: failure

**To Reproduce**
1. Use libthemis.wasm on a web page to encrypt and decrypt data with an input data size above 48000 bytes
2. Run '...'
3. See the following error:
```
Themis: SecureCellSeal: failure
```

**Expected behavior**
Expected it to decrypt the
**Environment (please complete the following information):**
- OS: macOS Big Sur v 11.2.2,  Safari 14.0.3
- Hardware: [32-bit/64-bit, or mobile device name and version]
- Themis version: [e.g. 0.12.0]
- Installation way:
   - [X ] via package manager
   - [ ] built from source

**Additional context**
Happens intermittently with an input data size around 48000 bytes. Larger input sizes happens all the time. Does not happen with much smaller sizes. Runs perfectly well on Chrome on macOS. After encryption if decryption is not done - this exception is thrown - RuntimeError: Out of Bounds memory access (evaluating 'libthemis$2._themis_secure_cell_encrypt_sel')

**Comment by vixentael** [comment]
Hi @CACUser!

Thank you for reporting, that looks interesting :)
I suspect some issues with data size / memory management in wasm wrapper. We will investigate.

Do you see this error every time on _any_ data larger than 48000 bytes? Or does this data have some special symbols inside?

**Comment by vixentael** [comment]
> Runs perfectly well on Chrome on macOS.

even with data above 48000 bytes?

**Comment by vixentael** [comment]
Thank you @CACUser! We will investigate this.

It will help a lot if you could send us a test project that reproduces the issue.

Also, we're in the middle of migrating to typescript for WASM themis #792, I'm wondering if this might help..

cc @ilammy

**Comment by maxammann** [comment]
> Also, we're in the middle of migrating to typescript for WASM themis #792, I'm wondering if this might help..
> 

Probably it wont as I did not really discover any implementation bugs while converting to ts.

**Comment by ilammy** [comment]
FWIW, I've been testing recently added WasmThemis example with recently released `wasm-themis@0.13.10` with Safari 14.0.3 as well, and it works fine for me. So it does not seem to be failing in isolation.

**Comment by vixentael** [comment]
i think this one is addressed by https://github.com/cossacklabs/themis/issues/928 and https://github.com/cossacklabs/themis/releases/tag/0.14.8

**Comment by radetsky** [comment]
@CACUser, please take a look, if you are still interested. You may update wasm-themis to the latest at the moment 0.14.8. 

I have checked twice with different browsers the issue with the code from https://github.com/radetsky/create-react-app-with-themis/tree/big_files_encryption_test 

It works fine even with 20 MB of data.
