### ISSUE TITLE
 Can I install themis inside alpine?

### ISSUE THREAD

**Issue by roccia** [cossacklabs/themis#839]
It seems themis installation only supprot debain , ubunut, I'm wondering if it works on alpine linux?

**Comment by ilammy** [comment]
Hey @roccia, thank you for your interest!

Yes, Themis works on Alpine Linux. However, at the moment Cossack Labs does not build packages for Alpine Linux so you will need to compile Themis from source:

```bash
apk add git                       # git to pull the source
apk add bash make gcc musl-dev    # build system dependencies
apk add openssl openssl-dev       # Themis dependencies

# Pull source code from GitHub:
git clone https://github.com/cossacklabs/themis
cd themis

make               # build
make test          # run test suite
make install       # install to /usr/local
```

This builds and installs Themis Core libraries which are necessary for high-level language wrappers to work if you want to use them.

Alpine Linux is not an officially fully supported platform, thus there are no official packages and no specific documentation for Alpine. However, it more or less “just works”.

**Comment by vixentael** [comment]
Thank you @ilammy! 

Yes, unfortunately right now we don't build ready-to-use binaries for Alpine.
After building and installing Themis Core (using steps @ilammy described above), you might need to install Themis language wrapper (Themis for python from pip, or for nodejs from npm, etc). Which languages do you plan to use?

https://docs.cossacklabs.com/themis/installation/installation-from-packages/#installing-themis-language-wrappers

**Comment by roccia** [comment]
thank you @ilammy 
@vixentael I'm using golang, so I just need install gothemis with go get right?

**Comment by vixentael** [comment]
First, install Themis Core on Alpine.
Then, install Themis Go using `go get`.

Here are the docs:
https://docs.cossacklabs.com/themis/languages/go/installation/

**Comment by roccia** [comment]
Got it Thank you
