### ISSUE TITLE
Ability to provide entropy when generating a keypair

### ISSUE THREAD

**Issue by steida** [cossacklabs/themis#892]
BIP85 describes a way how entropy can be derived deterministically from a BIP32 root key, for example, a BIP39 mnemonic (24 words) commonly used in cryptocurrency wallets.

The ability to derive a keypair directly from the mnemonic would improve Themis DX I suppose.

**Comment by vixentael** [comment]
thank you @steida , definitely smth to consider

**Comment by steida** [comment]
@vixentael ETA, please?

**Comment by vixentael** [comment]
@steida no ETA rn, as it's not one of the features users ask for. it's moved to a backlog to consider.

**Comment by dentropy** [comment]
@steida I am pretty sure you can just generate your own keys using another library like 

* https://www.npmjs.com/package/micro-key-producer - for EDCSA keys
* https://www.npmjs.com/package/seededrsa - for RSA keys
