### ISSUE TITLE
PHP Wrapper for Secure Message (Signed Message Variant)

### ISSUE THREAD

**Issue by mobrio** [cossacklabs/themis#9]
Code of the form:

$ka = phpthemis_gen_ec_key_pair();
$kb = phpthemis_gen_ec_key_pair();
$em = phpthemis_secure_message_wrap($ka['private_key'],$kb['public_key'],"My message");

works as expected producing an encrypted message. However, from themis_secure_message_wrap(...) in secure_message.c one would expect that passing NULL (or possibly a zero length string) for the public_key parameter would generate the "signed but not encrypted" version of the message. 

But both:

$em = phpthemis_secure_message_wrap($ka['private_key'],NULL,"My message");
$em = phpthemis_secure_message_wrap($ka['private_key'],'',"My message");

result in and empty string (gettype($em) == 'string') being returned. I suspect (via zend_parse_parameters ?) the public_key explicitly or implicitly ends up as an empty string (rather than NULL) so the clause in secure_message.c that would trigger "signing" rather than "encrypting" i.e. if(public_key==NULL && public_key_length==0) cannot happen.

**Comment by mobrio** [comment]
Confirmed as follows:
Amend line #74 in secure_message.c to be: 
`if(public_key==NULL || public_key_length==0)`
(public_key can be null **or** zero length) and:
`$em = phpthemis_secure_message_wrap($ka['private_key'],NULL,"My message");`
`$dm = phpthemis_secure_message_unwrap($kb['private_key'],$ka['public_key'],$em);`
works just fine.

**Comment by mnaza** [comment]
No, in line #74 in secure_message.c must be **and** because it using secure_message without public key is correct (with different flow but correct), and we must be shure that user not set public key by mistake. By this reason I set **&&** and signing will work only if public_key==NULL **and** public_key_length==NULL. In other case will be initialise encription mode witch return error because public_key is incorrect.

**Comment by mobrio** [comment]
Apologies - I merely meant that the change in line #74 **confirned** the nature of the problem **not** that it should be the solution - which no doubt should be somewhere in the php wrapper

**Comment by mnaza** [comment]
Thank You for comments. I understand and correct wrapper.

**Comment by mobrio** [comment]
And here's a solution to consider that enforces public_key to be either NULL or a string. The case of a zero length string could also be tested here but will be caught by the original `if(public_key==NULL && public_key_length==0)` in secure_message.c

In `phpthemis_secure_message_wrap` add initialisation to declarations of `public_key` and `public_key_length` :
```php
  char* public_key=NULL;
  int public_key_length=0;
```
parse the parameters like this:
```php
  zval* public_key_var;
  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "szs", &private_key, &private_key_length, &public_key_var, &message, &message_length) == FAILURE) {
    RETURN_NULL();
  }
  if (Z_TYPE_P(public_key_var) == IS_STRING) {
    public_key = Z_STRVAL_P(public_key_var);
    public_key_length = Z_STRLEN_P(public_key_var);
  }
  else if (Z_TYPE_P(public_key_var) != IS_NULL) {
    RETURN_NULL();
  }
```

**Comment by mnaza** [comment]
We can`t return NULL if public key is NULL, in this case secure_message produce signed wrapped message. Zend can parse NULL as string of zero length. In this case parsing of param may me like this:
```
char* public_key;
int public_key_length;
  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "sss", &private_key, &private_key_length, &public_key, &public_key_length, &message, &message_length) == FAILURE) {
    RETURN_NULL();
  }
if(!public_key_length){
     public_key=NULL;
}
```
in such implementation using of secure_message_wrap functions allow to set public key in NULL or in "" for produce signed wrapped message

**Comment by mobrio** [comment]
The snippet I proposed will only sign rather than encrypt if public_key_var is **explicitly** passed as NULL. It only returns NULL (at this level) iff public_key_var is neither a string nor NULL. ( "!=" != "==" ? ) 

Your snippet allows public_key to be passed as NULL (php type juggled to a zero length string) or '' (an explicit zero length string) or anything else that that ends up as a ZLS such as FALSE.

I prefer yours for brevity. Both work. The question is whether a signing requires a very deliberate choice of explicit NULL **or** a more forgiving "anything that ends up as" a ZLS is a better way to go.

**Comment by cossacklabs** [comment]
closed by commits https://github.com/cossacklabs/themis/commit/2dd201447fd4a19518abf150f6361e8c94599016
https://github.com/cossacklabs/themis/commit/ade4cc0197eb319c4d9597bbde270f2b44db0376
