### ISSUE TITLE
How to use themis webasm in react?

### ISSUE THREAD

**Issue by djaffer** [cossacklabs/themis#921]
I am trying to use themis with react but there is no documentation. Is it not supported?

I keep getting this error 
```
Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
```

**Comment by radetsky** [comment]
Hello! 
Could you provide more details? We need a context of what you want to do and an example with a code of how you are trying to do it.

**Comment by djaffer** [comment]
I want to use the library in react.

**Comment by radetsky** [comment]
Probably, you should read this: https://docs.cossacklabs.com/themis/languages/wasm/installation/

_However, in addition to JavaScript code, WasmThemis also includes the compiled WebAssembly bytecode. The bytecode is located in node_modules/wasm-themis/src/libthemis.wasm file, which will be loaded by the browser separately. Make sure that libthemis.wasm is placed next to the produced JavaScript bundle by copying it from node_modules directory when building your application._

You don't need to import it. Look at the example below: 
```
import { initialize, SymmetricKey } from 'wasm-themis';
componentDidMount() {
    initialize().then(() => {
      const key = new SymmetricKey();
      console.log(key)
    })
      .catch((err) => {
        console.log("Can not init: ", err);
      });
  }
```

**Comment by djaffer** [comment]
Thanks! Same error. Can you please try to get it working in codesandbox and share the link?

**Comment by djaffer** [comment]
Any update?

**Comment by radetsky** [comment]
We will make an example for react and share it on GitHub asap. Unfortunately, there was no time to finish this week.

**Comment by djaffer** [comment]
thank you!

**Comment by radetsky** [comment]
Please read this example https://github.com/radetsky/create-react-app-with-themis and give us feedback. 
Thank you!

**Comment by djaffer** [comment]
Great thank you so much!

**Comment by vixentael** [comment]
@djaffer please try and get back to us with feedback. If the example works for you, we will add it to the official guides

**Comment by djaffer** [comment]
I tried this way as it seemed simpler rather than having config-override to copy-paste the entire file. The initialization is slow, maybe it is supposed to be like this. Will try to add a loader until it does initialize. My future recommendation would be to make it lightweight for easier adoption, like web-crypto. Maybe a different use case is for this so you can ignore it. 

In nodejs it also requires various SSL package to work. All that should be abstracted so it can be used in alpine images. 

Also, just observing how come the encryption function is not async. Does it able to encrypt that fast? 

```
import themis from 'wasm-themis';
import libThemis from 'wasm-themis/dist/libthemis.wasm';

   await themis.initialize(libThemis);
    
 ```
 
 config-overide.js

 ```
 module.exports = (config, env) => {

   config.module.rules[1].oneOf.unshift({
    test: /\.wasm$/,
    type: 'javascript/auto',
    loader: 'file-loader',
  });
    return config;
};
```
