### ISSUE TITLE
react-native-themis - Native exceptions not catchable by JS code

### ISSUE THREAD

**Issue by tom-at-pixel** [cossacklabs/themis#925]
**Describe the bug**
When an exception is thrown in the native layer of `react-native-themis`, it is not propagated properly across the JS bridge and thus cannot be handled by the calling JavaScript code.

**To Reproduce**
1. In a React Native project with `react-native-themis` installed, run the following code:

```typescript
const key = "ANY_BYTE_ARRAY";
const invalidText = ""; // empty text will cause an exception

try {
    // This code will throw a native exception
    await secureCellSealWithSymmetricKeyEncrypt64(key, invalidText);
} catch (err) {
    // The error should be caught and we should end up in here
    console.error("We should get to this code, but we don't.");
}
```

2. Observe the uncaught exception:

![image](https://user-images.githubusercontent.com/109755647/180276161-3022463e-233b-4c72-8c64-a242de356def.png)

**Expected behavior**
The native error should be caught in the native layer and thrown in the JavaScript code so it can be handled appropriately.

**Environment (please complete the following information):**
- OS: iOS 15.2
- Hardware: iOS Simulator
- Themis version: react-native-themis 0.14.4
- Installation way:
   - [x] via package manager
   - [ ] built from source

**Comment by vixentael** [comment]
Thank you, @tom-at-pixel! Makes sense, we'll take a look.

**Comment by vixentael** [comment]
i guess it's fixed in the latest release 0.14.7
https://github.com/cossacklabs/themis/releases/tag/0.14.7

@tom-at-pixel please take a look

**Comment by tom-at-pixel** [comment]
@vixentael Thanks for getting back to me on this. I looked at the PRs of the fixes, and it seems that while the example I gave above has been addressed, the root cause has not: native exceptions are not being caught and passed to the JavaScript layer. The fixes throw JavaScript exceptions for invalid inputs, but the problem is that ANY uncaught native exception should be caught and passed to the JavaScript layer, which is what I created this issue for. The naive solution (which is perfectly fine, IMO), is to wrap the entry-point of any native code in a try {} catch {} and then pass any exception from the catch block to the JavaScript code, where it is thrown in the JS layer so that it can be caught by users of the library. Does that make sense? I can elaborate if not. With your permission, I'd like to re-open this issue.

**Comment by vixentael** [comment]
thank you @tom-at-pixel! it makes sense.

cc @rad @ilammy

**Comment by radetsky** [comment]
Ok, I'll catch it.

**Comment by radetsky** [comment]
@tom-at-pixel, thank you for your attention. We have rewritten our native code to catch any exceptions during execution in the native part. Please, take a look.
