### ISSUE TITLE
Please fix an important bug

### ISSUE THREAD

**Issue by DimaSergeew** [cossacklabs/themis#927]
Core server: mirai-paperclip-1.19-R0.1-SNAPSHOT-reobf.jar
Plugins version: Themis 0.13.0
OC: Linux
Dear developer, I have a problem on the server! I have the PVPManager plugin and when the players fight in PvP put a flag so that they don’t run away from the battle, so when this flag is put, the anti-cheat stops checking the players and they calmly fly and use the speed hack, as soon as the protection time passes they can’t use it again cheats. I wrote to the PvPManager developer, he said that there are no problems in his plugin and this is a problem in anti-cheat and I need to contact you

**Comment by vixentael** [comment]
@DimaSergeew / Vadim i don't think you are in the correct repository :)
