### ISSUE TITLE
Code signing issues with Themis Carthage

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#943]
May be similar to #940.

Installing Themis via carthage (for iOS and macOS) going ok, but then building a project returns code-signing error.

Here is what we use to install via Cathage (as carthage still has an issue where it tries to build _all_ xcodeprojs in the folder):

```carthage update --use-xcframeworks --no-build ; find . -type d -name 'ThemisTest.xcodeproj' -exec rm -r {} \; ; carthage build --use-xcframeworks```

When building app in Debug or Release mode, it doesn't work due to code signing error:

![CleanShot 2022-08-30 at 18 24 11@2x](https://user-images.githubusercontent.com/2877920/187497169-9cd283a9-f1d4-4877-bf53-ca78a6d805e6.png)
![CleanShot 2022-08-30 at 18 24 40@2x](https://user-images.githubusercontent.com/2877920/187497194-4e06e12b-55b7-4568-9ac4-1256dcddca20.png)

**Expected behavior**

Well.... it should work :)

**Environment (please complete the following information):**
- OS: iOS and macOS
- Hardware: 64bit, M1
- Themis version: latest
- Installation way:
   - carthage

The current hypothesis is that `xcframework` we have released previously for openssl and Themis are somehow different from the ones that Xcode generates now. Code-signing part different. We might need to re-release openssl and themis xcframeworks.

**Comment by vixentael** [comment]
cc @julepka

**Comment by vixentael** [comment]
Useful tip: https://stackoverflow.com/questions/68467306/the-code-signature-version-is-no-longer-supported

**Comment by vixentael** [comment]
Test project with only openssl xcframework linked:
https://www.dropbox.com/s/3grny4p6mq7pus7/TestXCFrameworks.zip?dl=0

**Comment by vixentael** [comment]
So, apparently it's not an issue.

We've investigated further, here problem was in adding openssl.xcframework and themis.xcframework both to the project. For couple of last versions, Themis supports openssl as static link, so no need to link them separately.

No work was done here.

**Comment by ilammy** [comment]
> here problem was in adding openssl.xcframework and themis.xcframework both to the project

That would still be a problem if you legitimately want to link them both, right?

Think, some other dependency wants OpenSSL. Our answer to that is, “This isn’t the library you’re looking for”. That is, please don’t use OpenSSL. Not being able to use OpenSSL is a known tradeoff for distributing Themis as a static library with OpenSSL baked into it.
