### ISSUE TITLE
Does this Library supports only for Android 7  and above devices

### ISSUE THREAD

**Issue by pradeep-orbi** [cossacklabs/themis#974]
Does this Library supports only for Android 7  and above devices ?

**Comment by vixentael** [comment]
Most likely even Android 8.1 (API level 27) and above

**Comment by vixentael** [comment]
If you want, you can follow the installation guide and test on lower Android devices:

https://docs.cossacklabs.com/themis/languages/kotlin/installation-android/

We don't do anything to specifically restrict the version, but the compilation pipeline uses Android 8.1
