### ISSUE TITLE
Is themis compatible with other encryption libraries

### ISSUE THREAD

**Issue by pradeep-orbi** [cossacklabs/themis#975]
Is themis compatible with android jetpack security library ?
Can a file encrypted with themis be decrypted using jetpack security library and vice versa ??

**Comment by vixentael** [comment]
Themis uses OpenSSL / BoringSSL under the hood, Android cryptography also uses BoringSSL. Thus when you use Themis Secure Cell Seal it uses the same AES-256-GCM as Android Jetpack security library. So Themis and Jetpack security use compatible crypto primitives, but the order of operations and details are different.

For example, Themis uses PBKDF2 as KDF while Jetpack security can use HKDF, and so on.

Themis and Jetpack security wrap data differently, the encrypted data from Jetpack security will have one format, the encrypted data from Themis Secure Cell will have another format.

It's not possible to encrypt data suing Themis and decrypt using Android Jetpack and vice versa.

**Comment by pradeep-orbi** [comment]
Thank you so much for the detailed answer.
