### ISSUE TITLE
react-native-themis not working with react-native 0.71.0

### ISSUE THREAD

**Issue by unixvb** [cossacklabs/themis#978]
**Describe the bug**
Empty `react-native` 0.71.0 project does not create an Android release build if `react-native-themis` is installed.

**To Reproduce**
1. `npx react-native init AwesomeProject`
2. `cd  AwesomeProject`
3. `yarn add react-native-themis`
4. `cd android && ./gradlew assembleRelease`
```
> Task :react-native-themis:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-themis:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/AwesomeProject/node_modules/react-native-themis/android/build/intermediates/merged_res/release/values/values.xml:2717: AAPT: error: resource android:attr/lStar not found.
         

```

**Expected behavior**
Successful build.

**Environment (please complete the following information):**
- OS: macOS 13.1 (22C65)
- Hardware: MacBook Pro 2019 Intel Core i9
- Themis version: 0.14.10
- Installation way:
   - [X] via package manager
   - [ ] built from source

**Additional context**

**Comment by vixentael** [comment]
more context: "We updated react-native to version 0.71 and it requires gradle 7.3.3 > 7.5.1 upgrade, which in turn causes an error"

**Comment by vixentael** [comment]
more context. last time it worked in the following configuration:

```
"react-native": "0.70.6"
"react-native-themis": "0.14.7",
```

**Comment by vixentael** [comment]
thank you @radetsky for fixing 👏 

@unixvb please take a look at new 0.14.11 hotfix for Themis RN and let us know if it works for you
 
https://github.com/cossacklabs/themis/releases/tag/0.14.11
https://www.npmjs.com/package/react-native-themis?activeTab=readme

**Comment by unixvb** [comment]
@vixentael perfect, everything works
Thank you!
