### ISSUE TITLE
Composer-friendly PHP wrapper?

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#98]
Study how Composer works, figure out what is necessary to wrap PHP library for Composer.

**Comment by mnaza** [comment]
If I understand correctly, composer can add php-extensions(phpthemis is extension) as requirements of php project but it can`t build and install it.

**Comment by gene-eu** [comment]
Leaving this for future - maybe someone someday will figure out how to benefit more from Composer

**Comment by gene-eu** [comment]
Thing is, we know that within PHP ecosystem there are some nifty packaging options, which will significantly simplify using Themis for PHP folks, but we're not aware of current PHP packaging trends, apart from knowing that there is Composer and it somehow helps :)

**Comment by gene-eu** [comment]
Formal criterias from `awesome-php`

Software that is PHP 5.5+, Composer-installable, PSR compliant, semantically versioned, unit tested

**Comment by gene-eu** [comment]
https://getcomposer.org/ - docs here, then submit here https://packagist.org/

**Comment by mnaza** [comment]
Composer can't install php extensions like `phpthemis`, in Composer terms called `platform paskages`. The only thing user can do is add line:
```
"ext-phpthemis": "*"
```
to `require` section of his `composer.json` in his project to check - is `phpthemis` installed in system.

Even if we create some php wrapper around phpthemis and create Composer paskage from it manual instalation of `phpthemis` will be require.

**Comment by gene-eu** [comment]
You mean we can't install php wrapper around themis as composer package or all of it? (obviously we can't build binaries through php, it's not that we expect to).

**Comment by vixentael** [comment]
We decided to distribute PHP wrapper via pre-built packages. Working on this right now. I'll post instructions here when we finish it.

**Comment by vixentael** [comment]
Okay, now you can install phpthemis downloading its package:
https://github.com/cossacklabs/themis/wiki/PHP-Howto#quickstart
