### ISSUE TITLE
Is pod a required step for react native via expo

### ISSUE THREAD

**Issue by djaffer** [cossacklabs/themis#981]
What is the purpose of the step below?

The documentation does not explain what is meant by it. 

```
cd ios
pod install 
```

**Comment by radetsky** [comment]
Thank you for your question.  

React Native Themis cannot be used under Expo without additional steps, because it requires libraries that are not written in JS.  To use React Native Themis we suggest beginning a new project with React Native CLI interface with XCode or Android Studio setup.
